apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.storageClass.secretName }}
  namespace: {{ .Values.global.storageClass.secretNamespace }}
type: kubernetes.io/lb-csi
data:
  jwt: |-
  {{ .Files.Get "lightos-jwt.toml" | b64enc | indent 2 }}
