apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.storageClass.name }}
provisioner: csi.lightbitslabs.com
allowVolumeExpansion: true
parameters:
  mgmt-endpoint: {{ (required "mgmtEndpoints field is required" .Values.global.storageClass.mgmtEndpoints) }}
  replica-count: {{ .Values.global.storageClass.replicaCount | quote }}
  compression: {{ .Values.global.storageClass.compression }}
  project-name: {{ .Values.global.storageClass.projectName }}
  mgmt-scheme: grpcs
{{- if and .Values.global.storageClass.secretName .Values.global.storageClass.secretNamespace }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ .Values.global.storageClass.secretName }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Values.global.storageClass.secretNamespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.global.storageClass.secretName }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Values.global.storageClass.secretNamespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.global.storageClass.secretName }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.global.storageClass.secretNamespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.global.storageClass.secretName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Values.global.storageClass.secretNamespace }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.global.storageClass.secretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.global.storageClass.secretNamespace }}
{{- end }}