apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.storageClass.name }}
provisioner: {{ (or .Values.global.storageClass.provisioner "csi.lightbitslabs.com") }}
allowVolumeExpansion: true
parameters:
  mgmt-endpoint: {{ (required "mgmtEndpoints field is required" .Values.global.storageClass.mgmtEndpoints) }}
  replica-count: {{ .Values.global.storageClass.replicaCount | quote }}
  compression: {{ .Values.global.storageClass.compression }}
  project-name: {{ .Values.global.storageClass.projectName }}
  mgmt-scheme: grpcs
{{- if .Values.global.storageClass.fsType }}
  csi.storage.k8s.io/fstype: {{ .Values.global.storageClass.fsType }}
{{- end }}
{{- if .Values.global.storageClass.qosPolicyName }}
  qos-policy-name: {{.Values.global.storageClass.qosPolicyName}}
{{- end }}
{{- if .Values.global.storageClass.hostEncryption }}
  host-encryption: {{.Values.global.storageClass.hostEncryption}}
{{- end }}
{{- if and .Values.global.jwtSecret.name .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
{{- end }}
