apiVersion: v2
name: lb-csi-plugin
version: 0.2.0
description: Helm Chart for LightOS CSI Plugin.
appVersion: 1.4.1
home: https://github.com/lightbitslabs/lb-csi
icon: https://www.lightbitslabs.com/wp-content/uploads/2018/08/cropped-header-logo-32x32.png
maintainers:
- name: Lightbits LTD
  email: support@lightbitslabs.com
  url: https://www.lightbitslabs.com/

