---
enableExpandVolume: true
enableSnapshot: true
image: "lb-csi-plugin:1.4.0"
imageRegistry: docker.lightbitslabs.com/lightos-csi
imagePullPolicy: IfNotPresent
imagePullSecret: ""
discoveryClientInContainer: false
discoveryClientImage: "lb-nvme-discovery-client:1.4.0"
controllerServiceAccountName: lb-csi-ctrl-sa
nodeServiceAccountName: lb-csi-node-sa
kubeletRootDir: /var/lib/kubelet
tlsSecrets: []
#registryUsername: ""
