---
enableExpandVolume: true
enableSnapshot: true
image: "lb-csi-plugin:1.10.0"
imageRegistry: docker.lightbitslabs.com/lightos-csi
sidecarImageRegistry: registry.k8s.io
imagePullPolicy: IfNotPresent
imagePullSecrets: []
discoveryClientInContainer: false
maxIOQueues: 0
discoveryClientImage: "lb-nvme-discovery-client:1.10.0"
controllerServiceAccountName: lb-csi-ctrl-sa
nodeServiceAccountName: lb-csi-node-sa
kubeletRootDir: /var/lib/kubelet
#luksConfigDir: /etc/lb-csi-luks-config
#registryUsername: ""
# jwtSecret:
# - name: cluster-admin-jwt
#   jwt: |-
#     ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTjVjM1JsYlRweWIyOTBJaXdpZEhsd0lqb2lTbGRVSW4wLmV5SmhkV1FpT2lKTWFXZG9kRTlUSWl3aVpYaHdJam94TmpRNU9UUXpNelkyTENKcFlYUWlPakUyTVRnME1EY3pOallzSW1semN5STZJbk41YzNSbGMzUnpJaXdpYW5ScElqb2lRMUJzTXpCdVNtVlFXV3hCU1dsRGJtMWpYMlJ2UVNJc0ltNWlaaUk2TVRZeE9EUXdOek0yTml3aWNtOXNaWE1pT2xzaWMzbHpkR1Z0T21Oc2RYTjBaWEl0WVdSdGFXNGlYU3dpYzNWaUlqb2liR2xuYUhSdmN5MWpiR2xsYm5RaWZRLm5PY2pTaTJlMUZ1RFhEMHRsYXFackZnQ2I2WFRqc19Lc2phUHRZbHBUMDZCNmQ5bmhfM1hIejNCRTZIUGJydVM3RERIT2xFOWZNUWpSbUl0LWZDZjJMQ0Jja1J6bm1fQnVGLU9wWGRQc2hDY1plX3VCeUFaTXNkMDJsR05fWHR2Sy03SXh3ZTZsSkd1S215dFdwWUhvcTczUVVfYUhITjItMHJJUFlWSEpfQmN4NDcxblQyRmQzbG5PSFNtNWVZWUhQTzJrcGdUSy0yMkVIX21FUWYxbldjQms3UU15T3RWbVloUmNwN0F3REhDLTllQkNnM0w2VDFFdlV1YWRMTXZpbXNGV2VWeXZya1ZVVzhrWjhZeDJTNlMzMG5FeFN2NHJ3aHVUX3Q4VnNyRFhnUWdWd0ZacGhiZ0dTZTBDQlR1dUNiMkt5TlRvVmxnQjBoQ05mUjBaZw==
