---

global:
  storageClass:
    name: example-sc
    # Name of the LightOS project we want the plugin to target.
    projectName: default
    # LightOS cluster API endpoints
    mgmtEndpoints: "" # required! comma delimited endpoints string, for example <ip>:<port>,<ip>:<port>
    # Number of replicas for each volume provisioned by this StorageClass
    replicaCount: "3"
    compression: disabled
  jwtSecret:
    name: example-secret
    namespace: default
    jwt: "" # required!

# subchart workloads:
storageclass:
  enabled: false
  # The csi.storage.k8s.io/fstype parameter is optional. The values allowed are ext4 or xfs. The default value is ext4.
  fstype: ""
block:
  enabled: false
  nodeSelector: {}
  nodeName: ""
filesystem:
  enabled: false
  nodeSelector: {}
  nodeName: "" # optional node name this pod will be deployed on.
preprovisioned:
  enabled: false
  lightosVolNguid: "" # required! nguid of LightOS volume.
  volumeMode: "" # required! one of ["Block", "Filesystem"]
  storage: "" # required! 1Gi
statefulset:
  enabled: false
  statefulSetName: example-sts
snaps:
  enabled: false
  pvcName: example-pvc
  stage: "" # required! one of ["example-pvc", "snapshot-from-pvc", "pvc-from-snapshot", "pvc-from-pvc", "snapshot-class", ""]
  snapshotStorageClass:
    name: example-snapshot-sc
