---
# Source: lb-csi-workload-examples/charts/block/templates/example-block-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-block-pvc
spec:
  storageClassName: "example-sc"
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 3Gi
---
# Source: lb-csi-workload-examples/charts/block/templates/example-block-pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: example-block-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - sleep
    - "1000000"
    imagePullPolicy: Always
    volumeDevices:
      - name: lb-csi-mount
        devicePath: /dev/lbcsiblkdev
  restartPolicy: "Never"
  volumes:
    - name: lb-csi-mount
      persistentVolumeClaim:
        claimName: example-block-pvc
