---
# Source: lb-csi-workload-examples/charts/snaps/templates/03.example-snapshot.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: example-snapshot
spec:
  volumeSnapshotClassName: "example-snapshot-sc"
  source:
    persistentVolumeClaimName: "example-pvc"
