{{- if and (required "snaps.stage field is required" .Values.stage) (eq .Values.stage "snapshot-class")}}
{{$kubeVersion := (or .Values.kubeVersion .Capabilities.KubeVersion.Version) | trimPrefix "v" }}
{{- if ($kubeVersion | semverCompare "< 1.20.0") }}
apiVersion: snapshot.storage.k8s.io/v1beta1
{{- else }}
apiVersion: snapshot.storage.k8s.io/v1
{{- end }}
kind: VolumeSnapshotClass
metadata:
  name: example-snapshot-sc
driver: {{ (or .Values.snapshotStorageClass.driver "csi.lightbitslabs.com") }}
deletionPolicy: Delete
{{- if and .Values.global.jwtSecret.name .Values.global.jwtSecret.namespace }}
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/snapshotter-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  csi.storage.k8s.io/snapshotter-list-secret-name: {{ .Values.global.jwtSecret.name }}
  csi.storage.k8s.io/snapshotter-list-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
  snapshot.storage.kubernetes.io/deletion-secret-name: {{ .Values.global.jwtSecret.name }}
  snapshot.storage.kubernetes.io/deletion-secret-namespace: {{ .Values.global.jwtSecret.namespace }}
{{- end }}
{{- end }}
