{{- if and (required "snaps.stage field is required" .Values.stage) (eq .Values.stage "snapshot-from-pvc")}}
{{$kubeVersion := (or .Values.kubeVersion .Capabilities.KubeVersion.Version) | trimPrefix "v" }}
{{- if ($kubeVersion | semverCompare "< 1.20.0") }}
apiVersion: snapshot.storage.k8s.io/v1beta1
{{- else }}
apiVersion: snapshot.storage.k8s.io/v1
{{- end }}
kind: VolumeSnapshot
metadata:
  name: example-snapshot
spec:
  volumeSnapshotClassName: {{ .Values.snapshotStorageClass.name | quote }}
  source:
    persistentVolumeClaimName: {{ .Values.pvcName | quote }}
{{- end }}
