{{$kubeVersion := (or .Values.kubeVersion .Capabilities.KubeVersion.Version) | trimPrefix "v" }}
{{- if ($kubeVersion | semverCompare "< 1.19.0") }}
apiVersion: storage.k8s.io/v1beta1
{{- else if ($kubeVersion | semverCompare ">= 1.19.0") }}
apiVersion: storage.k8s.io/v1
{{- end }}
kind: CSIDriver
metadata:
  name: {{ include "driver.fullname" . }}
  labels:
{{- include "mychart.labels" . | indent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
