# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: lb-csi-attacher-role
# rules:
#   - apiGroups: [""]
#     resources: ["persistentvolumes"]
#     verbs: ["get", "list", "watch", "update", "patch"]
#   - apiGroups: [""]
#     resources: ["nodes"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["storage.k8s.io"]
#     resources: ["volumeattachments"]
#     verbs: ["get", "list", "watch", "update", "patch"]
#   - apiGroups: ["storage.k8s.io"]
#     resources: ["csinodes"]
#     verbs: ["get", "list", "watch"]
# ---

# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: lb-csi-attacher-binding
# subjects:
#   - kind: ServiceAccount
#     name: {{ .Values.controllerServiceAccountName }}
#     namespace: {{ .Release.Namespace }}
# roleRef:
#   kind: ClusterRole
#   name: lb-csi-attacher-role
#   apiGroup: rbac.authorization.k8s.io


---
# Attacher must be able to work with PVs, CSINodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-external-attacher-runner-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
#Secret permission is optional.
#Enable it if you need value from secret.
#For example, you have key `csi.storage.k8s.io/controller-publish-secret-name` in StorageClass.parameters
#see https://kubernetes-csi.github.io/docs/secrets-and-credentials.html
#  - apiGroups: [""]
#    resources: ["secrets"]
#    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-csi-attacher-role-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllerServiceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: lb-external-attacher-runner-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
