---
kind: Pod
apiVersion: v1
metadata:
  name: {{ .Values.podName | quote }}
spec:
{{- if .Values.nodeSelector }}
  nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 4 }}
{{- end }}
{{- if .Values.nodeName }}
  nodeName: {{ .Values.nodeName }}
{{- end }}
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - sleep
    - "1000000"
    imagePullPolicy: Always
    volumeDevices:
      - name: lb-csi-mount
        devicePath: /dev/lbcsiblkdev
  restartPolicy: "Never"
  volumes:
    - name: lb-csi-mount
      persistentVolumeClaim:
        claimName: {{ .Values.pvcName | quote }}
