apiVersion: v1
kind: Pod
metadata:
  name: "example-pod"
spec:
  containers:
  - name: busybox
    imagePullPolicy: IfNotPresent
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh"]
    args: ["-c", "echo $KUBE_NODE_NAME >> /mnt/test/log; while true ; do date +%Y-%m-%d.%H-%M-%S >> /mnt/test/log ; sleep 5 ; done"]
    env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    stdin: true
    tty: true
    volumeMounts:
    - name: test-mnt
      mountPath: "/mnt/test"
  volumes:
  - name: test-mnt
    persistentVolumeClaim:
      claimName: "example-pvc"
