apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-from-snapshot
spec:
  storageClassName: example-sc
  dataSource:
    name: example-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
