apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-from-pvc
spec:
  storageClassName: example-sc
  dataSource:
    name: example-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
