// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-service/schedule_policy.proto

package durospb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DayOfWeek int32

const (
	DayOfWeek_DayOfWeekUnspecified DayOfWeek = 0
	DayOfWeek_Sunday               DayOfWeek = 1
	DayOfWeek_Monday               DayOfWeek = 2
	DayOfWeek_Tuesday              DayOfWeek = 3
	DayOfWeek_Wednesday            DayOfWeek = 4
	DayOfWeek_Thursday             DayOfWeek = 5
	DayOfWeek_Friday               DayOfWeek = 6
	DayOfWeek_Saturday             DayOfWeek = 7
)

var DayOfWeek_name = map[int32]string{
	0: "DayOfWeekUnspecified",
	1: "Sunday",
	2: "Monday",
	3: "Tuesday",
	4: "Wednesday",
	5: "Thursday",
	6: "Friday",
	7: "Saturday",
}

var DayOfWeek_value = map[string]int32{
	"DayOfWeekUnspecified": 0,
	"Sunday":               1,
	"Monday":               2,
	"Tuesday":              3,
	"Wednesday":            4,
	"Thursday":             5,
	"Friday":               6,
	"Saturday":             7,
}

func (x DayOfWeek) String() string {
	return proto.EnumName(DayOfWeek_name, int32(x))
}

func (DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{0}
}

type HourlySchedule struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	HoursInCycle         uint32               `protobuf:"varint,2,opt,name=hoursInCycle,proto3" json:"hoursInCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HourlySchedule) Reset()         { *m = HourlySchedule{} }
func (m *HourlySchedule) String() string { return proto.CompactTextString(m) }
func (*HourlySchedule) ProtoMessage()    {}
func (*HourlySchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{0}
}

func (m *HourlySchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HourlySchedule.Unmarshal(m, b)
}
func (m *HourlySchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HourlySchedule.Marshal(b, m, deterministic)
}
func (m *HourlySchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HourlySchedule.Merge(m, src)
}
func (m *HourlySchedule) XXX_Size() int {
	return xxx_messageInfo_HourlySchedule.Size(m)
}
func (m *HourlySchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_HourlySchedule.DiscardUnknown(m)
}

var xxx_messageInfo_HourlySchedule proto.InternalMessageInfo

func (m *HourlySchedule) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *HourlySchedule) GetHoursInCycle() uint32 {
	if m != nil {
		return m.HoursInCycle
	}
	return 0
}

type DailySchedule struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	DaysInCycle          uint32               `protobuf:"varint,2,opt,name=daysInCycle,proto3" json:"daysInCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DailySchedule) Reset()         { *m = DailySchedule{} }
func (m *DailySchedule) String() string { return proto.CompactTextString(m) }
func (*DailySchedule) ProtoMessage()    {}
func (*DailySchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{1}
}

func (m *DailySchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailySchedule.Unmarshal(m, b)
}
func (m *DailySchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailySchedule.Marshal(b, m, deterministic)
}
func (m *DailySchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailySchedule.Merge(m, src)
}
func (m *DailySchedule) XXX_Size() int {
	return xxx_messageInfo_DailySchedule.Size(m)
}
func (m *DailySchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_DailySchedule.DiscardUnknown(m)
}

var xxx_messageInfo_DailySchedule proto.InternalMessageInfo

func (m *DailySchedule) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *DailySchedule) GetDaysInCycle() uint32 {
	if m != nil {
		return m.DaysInCycle
	}
	return 0
}

type DayOfWeekEntry struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Day                  DayOfWeek            `protobuf:"varint,2,opt,name=day,proto3,enum=lightbits.api.schedule.DayOfWeek" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DayOfWeekEntry) Reset()         { *m = DayOfWeekEntry{} }
func (m *DayOfWeekEntry) String() string { return proto.CompactTextString(m) }
func (*DayOfWeekEntry) ProtoMessage()    {}
func (*DayOfWeekEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{2}
}

func (m *DayOfWeekEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayOfWeekEntry.Unmarshal(m, b)
}
func (m *DayOfWeekEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayOfWeekEntry.Marshal(b, m, deterministic)
}
func (m *DayOfWeekEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayOfWeekEntry.Merge(m, src)
}
func (m *DayOfWeekEntry) XXX_Size() int {
	return xxx_messageInfo_DayOfWeekEntry.Size(m)
}
func (m *DayOfWeekEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DayOfWeekEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DayOfWeekEntry proto.InternalMessageInfo

func (m *DayOfWeekEntry) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *DayOfWeekEntry) GetDay() DayOfWeek {
	if m != nil {
		return m.Day
	}
	return DayOfWeek_DayOfWeekUnspecified
}

type WeeklySchedule struct {
	DaysOfWeek           []*DayOfWeekEntry `protobuf:"bytes,1,rep,name=daysOfWeek,proto3" json:"daysOfWeek,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WeeklySchedule) Reset()         { *m = WeeklySchedule{} }
func (m *WeeklySchedule) String() string { return proto.CompactTextString(m) }
func (*WeeklySchedule) ProtoMessage()    {}
func (*WeeklySchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{3}
}

func (m *WeeklySchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeeklySchedule.Unmarshal(m, b)
}
func (m *WeeklySchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeeklySchedule.Marshal(b, m, deterministic)
}
func (m *WeeklySchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeeklySchedule.Merge(m, src)
}
func (m *WeeklySchedule) XXX_Size() int {
	return xxx_messageInfo_WeeklySchedule.Size(m)
}
func (m *WeeklySchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_WeeklySchedule.DiscardUnknown(m)
}

var xxx_messageInfo_WeeklySchedule proto.InternalMessageInfo

func (m *WeeklySchedule) GetDaysOfWeek() []*DayOfWeekEntry {
	if m != nil {
		return m.DaysOfWeek
	}
	return nil
}

type SnapshotSchedulePolicy struct {
	// Types that are valid to be assigned to SchedulePolicies:
	//	*SnapshotSchedulePolicy_HourlySchedule
	//	*SnapshotSchedulePolicy_DailySchedule
	//	*SnapshotSchedulePolicy_WeeklySchedule
	SchedulePolicies     isSnapshotSchedulePolicy_SchedulePolicies `protobuf_oneof:"schedulePolicies"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *SnapshotSchedulePolicy) Reset()         { *m = SnapshotSchedulePolicy{} }
func (m *SnapshotSchedulePolicy) String() string { return proto.CompactTextString(m) }
func (*SnapshotSchedulePolicy) ProtoMessage()    {}
func (*SnapshotSchedulePolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{4}
}

func (m *SnapshotSchedulePolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotSchedulePolicy.Unmarshal(m, b)
}
func (m *SnapshotSchedulePolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotSchedulePolicy.Marshal(b, m, deterministic)
}
func (m *SnapshotSchedulePolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotSchedulePolicy.Merge(m, src)
}
func (m *SnapshotSchedulePolicy) XXX_Size() int {
	return xxx_messageInfo_SnapshotSchedulePolicy.Size(m)
}
func (m *SnapshotSchedulePolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotSchedulePolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotSchedulePolicy proto.InternalMessageInfo

type isSnapshotSchedulePolicy_SchedulePolicies interface {
	isSnapshotSchedulePolicy_SchedulePolicies()
}

type SnapshotSchedulePolicy_HourlySchedule struct {
	HourlySchedule *HourlySchedule `protobuf:"bytes,1,opt,name=hourlySchedule,proto3,oneof"`
}

type SnapshotSchedulePolicy_DailySchedule struct {
	DailySchedule *DailySchedule `protobuf:"bytes,2,opt,name=dailySchedule,proto3,oneof"`
}

type SnapshotSchedulePolicy_WeeklySchedule struct {
	WeeklySchedule *WeeklySchedule `protobuf:"bytes,3,opt,name=weeklySchedule,proto3,oneof"`
}

func (*SnapshotSchedulePolicy_HourlySchedule) isSnapshotSchedulePolicy_SchedulePolicies() {}

func (*SnapshotSchedulePolicy_DailySchedule) isSnapshotSchedulePolicy_SchedulePolicies() {}

func (*SnapshotSchedulePolicy_WeeklySchedule) isSnapshotSchedulePolicy_SchedulePolicies() {}

func (m *SnapshotSchedulePolicy) GetSchedulePolicies() isSnapshotSchedulePolicy_SchedulePolicies {
	if m != nil {
		return m.SchedulePolicies
	}
	return nil
}

func (m *SnapshotSchedulePolicy) GetHourlySchedule() *HourlySchedule {
	if x, ok := m.GetSchedulePolicies().(*SnapshotSchedulePolicy_HourlySchedule); ok {
		return x.HourlySchedule
	}
	return nil
}

func (m *SnapshotSchedulePolicy) GetDailySchedule() *DailySchedule {
	if x, ok := m.GetSchedulePolicies().(*SnapshotSchedulePolicy_DailySchedule); ok {
		return x.DailySchedule
	}
	return nil
}

func (m *SnapshotSchedulePolicy) GetWeeklySchedule() *WeeklySchedule {
	if x, ok := m.GetSchedulePolicies().(*SnapshotSchedulePolicy_WeeklySchedule); ok {
		return x.WeeklySchedule
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SnapshotSchedulePolicy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SnapshotSchedulePolicy_HourlySchedule)(nil),
		(*SnapshotSchedulePolicy_DailySchedule)(nil),
		(*SnapshotSchedulePolicy_WeeklySchedule)(nil),
	}
}

type SchedulePolicy struct {
	// Types that are valid to be assigned to SchedulePolicies:
	//	*SchedulePolicy_SnapshotSchedulePolicy
	SchedulePolicies     isSchedulePolicy_SchedulePolicies `protobuf_oneof:"schedulePolicies"`
	RetentionTime        *duration.Duration                `protobuf:"bytes,2,opt,name=retentionTime,proto3" json:"retentionTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SchedulePolicy) Reset()         { *m = SchedulePolicy{} }
func (m *SchedulePolicy) String() string { return proto.CompactTextString(m) }
func (*SchedulePolicy) ProtoMessage()    {}
func (*SchedulePolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23f3dab9f27937f, []int{5}
}

func (m *SchedulePolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulePolicy.Unmarshal(m, b)
}
func (m *SchedulePolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulePolicy.Marshal(b, m, deterministic)
}
func (m *SchedulePolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulePolicy.Merge(m, src)
}
func (m *SchedulePolicy) XXX_Size() int {
	return xxx_messageInfo_SchedulePolicy.Size(m)
}
func (m *SchedulePolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulePolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulePolicy proto.InternalMessageInfo

type isSchedulePolicy_SchedulePolicies interface {
	isSchedulePolicy_SchedulePolicies()
}

type SchedulePolicy_SnapshotSchedulePolicy struct {
	SnapshotSchedulePolicy *SnapshotSchedulePolicy `protobuf:"bytes,1,opt,name=snapshotSchedulePolicy,proto3,oneof"`
}

func (*SchedulePolicy_SnapshotSchedulePolicy) isSchedulePolicy_SchedulePolicies() {}

func (m *SchedulePolicy) GetSchedulePolicies() isSchedulePolicy_SchedulePolicies {
	if m != nil {
		return m.SchedulePolicies
	}
	return nil
}

func (m *SchedulePolicy) GetSnapshotSchedulePolicy() *SnapshotSchedulePolicy {
	if x, ok := m.GetSchedulePolicies().(*SchedulePolicy_SnapshotSchedulePolicy); ok {
		return x.SnapshotSchedulePolicy
	}
	return nil
}

func (m *SchedulePolicy) GetRetentionTime() *duration.Duration {
	if m != nil {
		return m.RetentionTime
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchedulePolicy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchedulePolicy_SnapshotSchedulePolicy)(nil),
	}
}

func init() {
	proto.RegisterEnum("lightbits.api.schedule.DayOfWeek", DayOfWeek_name, DayOfWeek_value)
	proto.RegisterType((*HourlySchedule)(nil), "lightbits.api.schedule.HourlySchedule")
	proto.RegisterType((*DailySchedule)(nil), "lightbits.api.schedule.DailySchedule")
	proto.RegisterType((*DayOfWeekEntry)(nil), "lightbits.api.schedule.DayOfWeekEntry")
	proto.RegisterType((*WeeklySchedule)(nil), "lightbits.api.schedule.WeeklySchedule")
	proto.RegisterType((*SnapshotSchedulePolicy)(nil), "lightbits.api.schedule.SnapshotSchedulePolicy")
	proto.RegisterType((*SchedulePolicy)(nil), "lightbits.api.schedule.SchedulePolicy")
}

func init() { proto.RegisterFile("api-service/schedule_policy.proto", fileDescriptor_f23f3dab9f27937f) }

var fileDescriptor_f23f3dab9f27937f = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0xb4, 0xda, 0xb5, 0xb7, 0x9b, 0x58, 0x07, 0x29, 0xb1, 0x0f, 0xda, 0x0d, 0x28, 0x45,
	0x30, 0x85, 0xec, 0x8b, 0xe0, 0x83, 0xb0, 0xd6, 0xa5, 0x3e, 0x2c, 0x2e, 0x69, 0x65, 0xc5, 0x17,
	0x99, 0x26, 0xd3, 0x66, 0xd8, 0x34, 0x13, 0xe6, 0x63, 0x25, 0x4f, 0xe2, 0x2f, 0xf1, 0x27, 0xf9,
	0x97, 0x64, 0x26, 0x6d, 0x4d, 0x6a, 0xab, 0x0f, 0xfa, 0x94, 0xb9, 0xc9, 0xb9, 0xe7, 0x9c, 0x7b,
	0xe6, 0x06, 0x4e, 0x71, 0x4e, 0x5f, 0x08, 0xc2, 0x6f, 0x69, 0x44, 0x46, 0x22, 0x4a, 0x48, 0xac,
	0x52, 0xf2, 0x39, 0x67, 0x29, 0x8d, 0x0a, 0x3f, 0xe7, 0x4c, 0x32, 0xd4, 0x4b, 0xe9, 0x32, 0x91,
	0x73, 0x2a, 0x85, 0x8f, 0x73, 0xea, 0x6f, 0x40, 0xfd, 0x27, 0x4b, 0xc6, 0x96, 0x29, 0x19, 0x19,
	0xd4, 0x5c, 0x2d, 0x46, 0x92, 0xae, 0x88, 0x90, 0x78, 0x95, 0x97, 0x8d, 0xfd, 0xc7, 0xbb, 0x80,
	0x58, 0x71, 0x2c, 0x29, 0xcb, 0xca, 0xef, 0x5e, 0x06, 0xce, 0x84, 0x29, 0x9e, 0x16, 0xd3, 0x35,
	0x25, 0x7a, 0x09, 0x6d, 0x21, 0x31, 0x97, 0x33, 0xba, 0x22, 0xae, 0x35, 0xb0, 0x86, 0x9d, 0xa0,
	0xef, 0x97, 0x2c, 0xfe, 0x86, 0xc5, 0x9f, 0x6d, 0x64, 0xc2, 0x5f, 0x60, 0xe4, 0xc1, 0x49, 0xc2,
	0x14, 0x17, 0xef, 0xb2, 0x37, 0x45, 0x94, 0x12, 0xb7, 0x31, 0xb0, 0x86, 0x76, 0x58, 0x7b, 0xe7,
	0xdd, 0x80, 0x3d, 0xc6, 0xf4, 0xbf, 0xc8, 0x0d, 0xa0, 0x13, 0xe3, 0x62, 0x47, 0xad, 0xfa, 0xca,
	0xfb, 0x0a, 0xce, 0x18, 0x17, 0xef, 0x17, 0xd7, 0x84, 0xdc, 0xbc, 0xcd, 0x24, 0x2f, 0xfe, 0x41,
	0xed, 0x0c, 0x9a, 0x31, 0x2e, 0x8c, 0x8a, 0x13, 0x9c, 0xfa, 0xfb, 0xef, 0xc3, 0xdf, 0xca, 0x85,
	0x1a, 0xed, 0x7d, 0x04, 0x47, 0x17, 0x95, 0x71, 0x2f, 0x00, 0xb4, 0xc3, 0x12, 0xe4, 0x5a, 0x83,
	0xe6, 0xb0, 0x13, 0x3c, 0xfb, 0x2b, 0x9b, 0x31, 0x1f, 0x56, 0x3a, 0xbd, 0xef, 0x0d, 0xe8, 0x4d,
	0x33, 0x9c, 0x8b, 0x84, 0xc9, 0x0d, 0xf9, 0x95, 0xd9, 0x18, 0x74, 0x05, 0x4e, 0x52, 0xbb, 0xd2,
	0xf5, 0xa0, 0x07, 0x65, 0xea, 0x0b, 0x30, 0x39, 0x0a, 0x77, 0xfa, 0xd1, 0x25, 0xd8, 0x71, 0xf5,
	0xd2, 0x4c, 0x0a, 0x9d, 0xe0, 0xe9, 0x61, 0xdf, 0xb4, 0xc6, 0x57, 0xef, 0xd6, 0x06, 0xbf, 0xd4,
	0x52, 0x71, 0x9b, 0x7f, 0x36, 0x58, 0xcf, 0x50, 0x1b, 0xac, 0xf7, 0x9f, 0x23, 0xe8, 0x8a, 0x6a,
	0x08, 0x94, 0x08, 0xef, 0x87, 0x05, 0xce, 0x4e, 0x32, 0x09, 0xf4, 0xc4, 0xde, 0xcc, 0xd6, 0x09,
	0xf9, 0x87, 0x0c, 0xec, 0x4f, 0x7a, 0x72, 0x14, 0x1e, 0xe0, 0x43, 0xaf, 0xc1, 0xe6, 0x44, 0x92,
	0x4c, 0xff, 0x69, 0x66, 0xd7, 0xca, 0xc4, 0x1e, 0xfd, 0xb6, 0x6b, 0xe3, 0xf5, 0xef, 0x18, 0xd6,
	0xf1, 0xfb, 0x26, 0x7a, 0xfe, 0xcd, 0x82, 0xf6, 0x76, 0x25, 0x90, 0x0b, 0x0f, 0xb7, 0xc5, 0x87,
	0x4c, 0xe4, 0x24, 0xa2, 0x0b, 0x4a, 0xe2, 0xee, 0x11, 0x02, 0x68, 0x4d, 0x55, 0x16, 0xe3, 0xa2,
	0x6b, 0xe9, 0xf3, 0x25, 0x33, 0xe7, 0x06, 0xea, 0xc0, 0xf1, 0x4c, 0x11, 0xa1, 0x8b, 0x26, 0xb2,
	0xa1, 0x7d, 0x4d, 0xe2, 0xac, 0x2c, 0xef, 0xa0, 0x13, 0xb8, 0x37, 0x4b, 0x14, 0x37, 0xd5, 0x5d,
	0xdd, 0x75, 0xc1, 0xa9, 0x3e, 0xb7, 0xf4, 0x97, 0x29, 0x96, 0x8a, 0xeb, 0xea, 0xf8, 0xfc, 0xc1,
	0xa7, 0xfb, 0xb1, 0xe2, 0x4c, 0xdc, 0x06, 0xaf, 0xcc, 0x33, 0x9f, 0xcf, 0x5b, 0x66, 0x98, 0xb3,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x1c, 0x2a, 0xe2, 0xc7, 0x04, 0x00, 0x00,
}
