// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_apis/cluster.proto

package common_apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStateEnum int32

const (
	NodeStateEnum_Inactive NodeStateEnum = 0
	// node is is coming up (BE recovery..)
	NodeStateEnum_Activating NodeStateEnum = 1
	// datapath backend and frontend is up and we are listening on nvme and replication.
	//
	// Ready to be called AddPeer on.
	NodeStateEnum_Joining NodeStateEnum = 2
	// Sync the datapath, rebuild process start, and polling for completed state.
	NodeStateEnum_Rebuilding NodeStateEnum = 3
	// Rebuild completed
	NodeStateEnum_RebuildDone NodeStateEnum = 4
	// Rebuild completed, node joined cluster
	NodeStateEnum_Active       NodeStateEnum = 5
	NodeStateEnum_Deactivating NodeStateEnum = 6
	// any failure in the FE, BE, other...
	NodeStateEnum_Failed NodeStateEnum = 7
)

var NodeStateEnum_name = map[int32]string{
	0: "Inactive",
	1: "Activating",
	2: "Joining",
	3: "Rebuilding",
	4: "RebuildDone",
	5: "Active",
	6: "Deactivating",
	7: "Failed",
}

var NodeStateEnum_value = map[string]int32{
	"Inactive":     0,
	"Activating":   1,
	"Joining":      2,
	"Rebuilding":   3,
	"RebuildDone":  4,
	"Active":       5,
	"Deactivating": 6,
	"Failed":       7,
}

func (x NodeStateEnum) String() string {
	return proto.EnumName(NodeStateEnum_name, int32(x))
}

func (NodeStateEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{0}
}

// machine readable internal state of the node we want to report to the cluster.
type NodeStatusEnum int32

const (
	// reported during NodeStateEnum==Activating
	NodeStatusEnum_PowerupDatapath       NodeStatusEnum = 0
	NodeStatusEnum_PowerupDatapathFailed NodeStatusEnum = 1
	// reported during NodeStateEnum==Joining
	NodeStatusEnum_SyncDatapath     NodeStatusEnum = 2
	NodeStatusEnum_RebuildStarted   NodeStatusEnum = 3
	NodeStatusEnum_RebuildFailed    NodeStatusEnum = 4
	NodeStatusEnum_RebuildCompleted NodeStatusEnum = 5
	// reported during NodeStateEnum==Deactivating
	NodeStatusEnum_TeardownDatapath       NodeStatusEnum = 6
	NodeStatusEnum_TeardownDatapathFailed NodeStatusEnum = 7
	// reported during NodeStateEnum==Active
	NodeStatusEnum_RejoinStarted NodeStatusEnum = 8
	NodeStatusEnum_NodeJoined    NodeStatusEnum = 9
)

var NodeStatusEnum_name = map[int32]string{
	0: "PowerupDatapath",
	1: "PowerupDatapathFailed",
	2: "SyncDatapath",
	3: "RebuildStarted",
	4: "RebuildFailed",
	5: "RebuildCompleted",
	6: "TeardownDatapath",
	7: "TeardownDatapathFailed",
	8: "RejoinStarted",
	9: "NodeJoined",
}

var NodeStatusEnum_value = map[string]int32{
	"PowerupDatapath":        0,
	"PowerupDatapathFailed":  1,
	"SyncDatapath":           2,
	"RebuildStarted":         3,
	"RebuildFailed":          4,
	"RebuildCompleted":       5,
	"TeardownDatapath":       6,
	"TeardownDatapathFailed": 7,
	"RejoinStarted":          8,
	"NodeJoined":             9,
}

func (x NodeStatusEnum) String() string {
	return proto.EnumName(NodeStatusEnum_name, int32(x))
}

func (NodeStatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{1}
}

type ServerStateEnum_State int32

const (
	ServerStateEnum_Unknown   ServerStateEnum_State = 0
	ServerStateEnum_Creating  ServerStateEnum_State = 1
	ServerStateEnum_Enabled   ServerStateEnum_State = 2
	ServerStateEnum_Deleting  ServerStateEnum_State = 3
	ServerStateEnum_Failed    ServerStateEnum_State = 4
	ServerStateEnum_Disabled  ServerStateEnum_State = 5
	ServerStateEnum_Enabling  ServerStateEnum_State = 6
	ServerStateEnum_Disabling ServerStateEnum_State = 7
)

var ServerStateEnum_State_name = map[int32]string{
	0: "Unknown",
	1: "Creating",
	2: "Enabled",
	3: "Deleting",
	4: "Failed",
	5: "Disabled",
	6: "Enabling",
	7: "Disabling",
}

var ServerStateEnum_State_value = map[string]int32{
	"Unknown":   0,
	"Creating":  1,
	"Enabled":   2,
	"Deleting":  3,
	"Failed":    4,
	"Disabled":  5,
	"Enabling":  6,
	"Disabling": 7,
}

func (x ServerStateEnum_State) String() string {
	return proto.EnumName(ServerStateEnum_State_name, int32(x))
}

func (ServerStateEnum_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{0, 0}
}

type ServerUpgradeStatus_UpgradeStatusEnum int32

const (
	ServerUpgradeStatus_Unknown   ServerUpgradeStatus_UpgradeStatusEnum = 0
	ServerUpgradeStatus_None      ServerUpgradeStatus_UpgradeStatusEnum = 1
	ServerUpgradeStatus_Failed    ServerUpgradeStatus_UpgradeStatusEnum = 2
	ServerUpgradeStatus_Upgrading ServerUpgradeStatus_UpgradeStatusEnum = 3
	ServerUpgradeStatus_Rebooting ServerUpgradeStatus_UpgradeStatusEnum = 4
)

var ServerUpgradeStatus_UpgradeStatusEnum_name = map[int32]string{
	0: "Unknown",
	1: "None",
	2: "Failed",
	3: "Upgrading",
	4: "Rebooting",
}

var ServerUpgradeStatus_UpgradeStatusEnum_value = map[string]int32{
	"Unknown":   0,
	"None":      1,
	"Failed":    2,
	"Upgrading": 3,
	"Rebooting": 4,
}

func (x ServerUpgradeStatus_UpgradeStatusEnum) String() string {
	return proto.EnumName(ServerUpgradeStatus_UpgradeStatusEnum_name, int32(x))
}

func (ServerUpgradeStatus_UpgradeStatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{1, 0}
}

type UpgradeabilityEnum_State int32

const (
	UpgradeabilityEnum_None           UpgradeabilityEnum_State = 0
	UpgradeabilityEnum_Upgradeable    UpgradeabilityEnum_State = 1
	UpgradeabilityEnum_NonUpgradeable UpgradeabilityEnum_State = 2
	UpgradeabilityEnum_Failed         UpgradeabilityEnum_State = 3
)

var UpgradeabilityEnum_State_name = map[int32]string{
	0: "None",
	1: "Upgradeable",
	2: "NonUpgradeable",
	3: "Failed",
}

var UpgradeabilityEnum_State_value = map[string]int32{
	"None":           0,
	"Upgradeable":    1,
	"NonUpgradeable": 2,
	"Failed":         3,
}

func (x UpgradeabilityEnum_State) String() string {
	return proto.EnumName(UpgradeabilityEnum_State_name, int32(x))
}

func (UpgradeabilityEnum_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{2, 0}
}

type ServiceStatus_StateEnum int32

const (
	ServiceStatus_Failed       ServiceStatus_StateEnum = 0
	ServiceStatus_Initializing ServiceStatus_StateEnum = 1
	ServiceStatus_Disconnected ServiceStatus_StateEnum = 2
	ServiceStatus_Connected    ServiceStatus_StateEnum = 3
)

var ServiceStatus_StateEnum_name = map[int32]string{
	0: "Failed",
	1: "Initializing",
	2: "Disconnected",
	3: "Connected",
}

var ServiceStatus_StateEnum_value = map[string]int32{
	"Failed":       0,
	"Initializing": 1,
	"Disconnected": 2,
	"Connected":    3,
}

func (x ServiceStatus_StateEnum) String() string {
	return proto.EnumName(ServiceStatus_StateEnum_name, int32(x))
}

func (ServiceStatus_StateEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{7, 0}
}

type ServiceStatus_ModeEnum int32

const (
	ServiceStatus_Passive      ServiceStatus_ModeEnum = 0
	ServiceStatus_Deactivating ServiceStatus_ModeEnum = 1
	ServiceStatus_Active       ServiceStatus_ModeEnum = 2
)

var ServiceStatus_ModeEnum_name = map[int32]string{
	0: "Passive",
	1: "Deactivating",
	2: "Active",
}

var ServiceStatus_ModeEnum_value = map[string]int32{
	"Passive":      0,
	"Deactivating": 1,
	"Active":       2,
}

func (x ServiceStatus_ModeEnum) String() string {
	return proto.EnumName(ServiceStatus_ModeEnum_name, int32(x))
}

func (ServiceStatus_ModeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{7, 1}
}

type ClusterReportedNodeState_StateEnum int32

const (
	ClusterReportedNodeState_Unknown ClusterReportedNodeState_StateEnum = 0
	// Deactivated node/ node not part of cluster
	ClusterReportedNodeState_Inactive ClusterReportedNodeState_StateEnum = 1
	// Node start up and joing cluster completed.
	ClusterReportedNodeState_Active ClusterReportedNodeState_StateEnum = 2
	//Joinging state part of join to cluster states
	ClusterReportedNodeState_Joining ClusterReportedNodeState_StateEnum = 3
	// node handlign request to deactivate (maintanence) node
	ClusterReportedNodeState_InactiveRequest ClusterReportedNodeState_StateEnum = 4
	// node experienced error in failed state
	ClusterReportedNodeState_Failed ClusterReportedNodeState_StateEnum = 5
)

var ClusterReportedNodeState_StateEnum_name = map[int32]string{
	0: "Unknown",
	1: "Inactive",
	2: "Active",
	3: "Joining",
	4: "InactiveRequest",
	5: "Failed",
}

var ClusterReportedNodeState_StateEnum_value = map[string]int32{
	"Unknown":         0,
	"Inactive":        1,
	"Active":          2,
	"Joining":         3,
	"InactiveRequest": 4,
	"Failed":          5,
}

func (x ClusterReportedNodeState_StateEnum) String() string {
	return proto.EnumName(ClusterReportedNodeState_StateEnum_name, int32(x))
}

func (ClusterReportedNodeState_StateEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{8, 0}
}

// machine readable internal state of the node we want to report to the cluster.
type ClusterReportedNodeState_StatusEnum int32

const (
	ClusterReportedNodeState_NoStatus ClusterReportedNodeState_StatusEnum = 0
	// reported during NodeStateEnum==Adding
	ClusterReportedNodeState_ConnectivityOK      ClusterReportedNodeState_StatusEnum = 1
	ClusterReportedNodeState_ConnectivityProblem ClusterReportedNodeState_StatusEnum = 2
	// reported during NodeStateEnum==Removing
	ClusterReportedNodeState_IssuedDeletePeer ClusterReportedNodeState_StatusEnum = 3
)

var ClusterReportedNodeState_StatusEnum_name = map[int32]string{
	0: "NoStatus",
	1: "ConnectivityOK",
	2: "ConnectivityProblem",
	3: "IssuedDeletePeer",
}

var ClusterReportedNodeState_StatusEnum_value = map[string]int32{
	"NoStatus":            0,
	"ConnectivityOK":      1,
	"ConnectivityProblem": 2,
	"IssuedDeletePeer":    3,
}

func (x ClusterReportedNodeState_StatusEnum) String() string {
	return proto.EnumName(ClusterReportedNodeState_StatusEnum_name, int32(x))
}

func (ClusterReportedNodeState_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{8, 1}
}

type Server_StateEnum int32

const (
	Server_Unknown   Server_StateEnum = 0
	Server_Active    Server_StateEnum = 1
	Server_Upgrading Server_StateEnum = 2
	Server_Inactive  Server_StateEnum = 3
)

var Server_StateEnum_name = map[int32]string{
	0: "Unknown",
	1: "Active",
	2: "Upgrading",
	3: "Inactive",
}

var Server_StateEnum_value = map[string]int32{
	"Unknown":   0,
	"Active":    1,
	"Upgrading": 2,
	"Inactive":  3,
}

func (x Server_StateEnum) String() string {
	return proto.EnumName(Server_StateEnum_name, int32(x))
}

func (Server_StateEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{10, 0}
}

type ServiceInfo_Type int32

const (
	ServiceInfo_ClusterManager ServiceInfo_Type = 0
	ServiceInfo_UpgradeManager ServiceInfo_Type = 1
)

var ServiceInfo_Type_name = map[int32]string{
	0: "ClusterManager",
	1: "UpgradeManager",
}

var ServiceInfo_Type_value = map[string]int32{
	"ClusterManager": 0,
	"UpgradeManager": 1,
}

func (x ServiceInfo_Type) String() string {
	return proto.EnumName(ServiceInfo_Type_name, int32(x))
}

func (ServiceInfo_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{11, 0}
}

type ServerStateEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStateEnum) Reset()         { *m = ServerStateEnum{} }
func (m *ServerStateEnum) String() string { return proto.CompactTextString(m) }
func (*ServerStateEnum) ProtoMessage()    {}
func (*ServerStateEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{0}
}

func (m *ServerStateEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStateEnum.Unmarshal(m, b)
}
func (m *ServerStateEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStateEnum.Marshal(b, m, deterministic)
}
func (m *ServerStateEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStateEnum.Merge(m, src)
}
func (m *ServerStateEnum) XXX_Size() int {
	return xxx_messageInfo_ServerStateEnum.Size(m)
}
func (m *ServerStateEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStateEnum.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStateEnum proto.InternalMessageInfo

type ServerUpgradeStatus struct {
	TypeMeta             *TypeMeta                             `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	ServerUUID           string                                `protobuf:"bytes,2,opt,name=serverUUID,proto3" json:"serverUUID,omitempty"`
	ServerName           string                                `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	UpgradeStatus        ServerUpgradeStatus_UpgradeStatusEnum `protobuf:"varint,4,opt,name=UpgradeStatus,proto3,enum=lightbits.api.ServerUpgradeStatus_UpgradeStatusEnum" json:"UpgradeStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ServerUpgradeStatus) Reset()         { *m = ServerUpgradeStatus{} }
func (m *ServerUpgradeStatus) String() string { return proto.CompactTextString(m) }
func (*ServerUpgradeStatus) ProtoMessage()    {}
func (*ServerUpgradeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{1}
}

func (m *ServerUpgradeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUpgradeStatus.Unmarshal(m, b)
}
func (m *ServerUpgradeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUpgradeStatus.Marshal(b, m, deterministic)
}
func (m *ServerUpgradeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUpgradeStatus.Merge(m, src)
}
func (m *ServerUpgradeStatus) XXX_Size() int {
	return xxx_messageInfo_ServerUpgradeStatus.Size(m)
}
func (m *ServerUpgradeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUpgradeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUpgradeStatus proto.InternalMessageInfo

func (m *ServerUpgradeStatus) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ServerUpgradeStatus) GetServerUUID() string {
	if m != nil {
		return m.ServerUUID
	}
	return ""
}

func (m *ServerUpgradeStatus) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *ServerUpgradeStatus) GetUpgradeStatus() ServerUpgradeStatus_UpgradeStatusEnum {
	if m != nil {
		return m.UpgradeStatus
	}
	return ServerUpgradeStatus_Unknown
}

type UpgradeabilityEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeabilityEnum) Reset()         { *m = UpgradeabilityEnum{} }
func (m *UpgradeabilityEnum) String() string { return proto.CompactTextString(m) }
func (*UpgradeabilityEnum) ProtoMessage()    {}
func (*UpgradeabilityEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{2}
}

func (m *UpgradeabilityEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeabilityEnum.Unmarshal(m, b)
}
func (m *UpgradeabilityEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeabilityEnum.Marshal(b, m, deterministic)
}
func (m *UpgradeabilityEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeabilityEnum.Merge(m, src)
}
func (m *UpgradeabilityEnum) XXX_Size() int {
	return xxx_messageInfo_UpgradeabilityEnum.Size(m)
}
func (m *UpgradeabilityEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeabilityEnum.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeabilityEnum proto.InternalMessageInfo

type ClusterInfo struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// a unique value for the entire cluster. should not change once it is added
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	SubsystemNqn         string   `protobuf:"bytes,3,opt,name=subsystemNqn,proto3" json:"subsystemNqn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterInfo) Reset()         { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()    {}
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{3}
}

func (m *ClusterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfo.Unmarshal(m, b)
}
func (m *ClusterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfo.Marshal(b, m, deterministic)
}
func (m *ClusterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfo.Merge(m, src)
}
func (m *ClusterInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterInfo.Size(m)
}
func (m *ClusterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfo proto.InternalMessageInfo

func (m *ClusterInfo) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ClusterInfo) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ClusterInfo) GetSubsystemNqn() string {
	if m != nil {
		return m.SubsystemNqn
	}
	return ""
}

type ClusterPeer struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID     string    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// friendly name of the node
	PeerName             string   `protobuf:"bytes,3,opt,name=peerName,proto3" json:"peerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterPeer) Reset()         { *m = ClusterPeer{} }
func (m *ClusterPeer) String() string { return proto.CompactTextString(m) }
func (*ClusterPeer) ProtoMessage()    {}
func (*ClusterPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{4}
}

func (m *ClusterPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPeer.Unmarshal(m, b)
}
func (m *ClusterPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPeer.Marshal(b, m, deterministic)
}
func (m *ClusterPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPeer.Merge(m, src)
}
func (m *ClusterPeer) XXX_Size() int {
	return xxx_messageInfo_ClusterPeer.Size(m)
}
func (m *ClusterPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPeer.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPeer proto.InternalMessageInfo

func (m *ClusterPeer) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ClusterPeer) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ClusterPeer) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

type ClusterPeerHeartbeat struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID     string    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// friendly name of the node
	PeerName             string               `protobuf:"bytes,3,opt,name=peerName,proto3" json:"peerName,omitempty"`
	Heartbeat            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClusterPeerHeartbeat) Reset()         { *m = ClusterPeerHeartbeat{} }
func (m *ClusterPeerHeartbeat) String() string { return proto.CompactTextString(m) }
func (*ClusterPeerHeartbeat) ProtoMessage()    {}
func (*ClusterPeerHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{5}
}

func (m *ClusterPeerHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPeerHeartbeat.Unmarshal(m, b)
}
func (m *ClusterPeerHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPeerHeartbeat.Marshal(b, m, deterministic)
}
func (m *ClusterPeerHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPeerHeartbeat.Merge(m, src)
}
func (m *ClusterPeerHeartbeat) XXX_Size() int {
	return xxx_messageInfo_ClusterPeerHeartbeat.Size(m)
}
func (m *ClusterPeerHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPeerHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPeerHeartbeat proto.InternalMessageInfo

func (m *ClusterPeerHeartbeat) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ClusterPeerHeartbeat) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ClusterPeerHeartbeat) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func (m *ClusterPeerHeartbeat) GetHeartbeat() *timestamp.Timestamp {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

type PeerCommand struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID     string    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Events   []*Event  `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	// friendly name of the node
	PeerName             string   `protobuf:"bytes,4,opt,name=peerName,proto3" json:"peerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerCommand) Reset()         { *m = PeerCommand{} }
func (m *PeerCommand) String() string { return proto.CompactTextString(m) }
func (*PeerCommand) ProtoMessage()    {}
func (*PeerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{6}
}

func (m *PeerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerCommand.Unmarshal(m, b)
}
func (m *PeerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerCommand.Marshal(b, m, deterministic)
}
func (m *PeerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerCommand.Merge(m, src)
}
func (m *PeerCommand) XXX_Size() int {
	return xxx_messageInfo_PeerCommand.Size(m)
}
func (m *PeerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_PeerCommand proto.InternalMessageInfo

func (m *PeerCommand) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *PeerCommand) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *PeerCommand) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *PeerCommand) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

type ServiceStatus struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID     string    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// friendly name of the server
	ServerName           string                  `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	State                ServiceStatus_StateEnum `protobuf:"varint,4,opt,name=state,proto3,enum=lightbits.api.ServiceStatus_StateEnum" json:"state,omitempty"`
	Error                string                  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Heartbeat            *timestamp.Timestamp    `protobuf:"bytes,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Mode                 ServiceStatus_ModeEnum  `protobuf:"varint,7,opt,name=mode,proto3,enum=lightbits.api.ServiceStatus_ModeEnum" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{7}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ServiceStatus) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ServiceStatus) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *ServiceStatus) GetState() ServiceStatus_StateEnum {
	if m != nil {
		return m.State
	}
	return ServiceStatus_Failed
}

func (m *ServiceStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ServiceStatus) GetHeartbeat() *timestamp.Timestamp {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

func (m *ServiceStatus) GetMode() ServiceStatus_ModeEnum {
	if m != nil {
		return m.Mode
	}
	return ServiceStatus_Passive
}

type ClusterReportedNodeState struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// service UUID
	UUID                 string                              `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	State                ClusterReportedNodeState_StateEnum  `protobuf:"varint,3,opt,name=state,proto3,enum=lightbits.api.ClusterReportedNodeState_StateEnum" json:"state,omitempty"`
	Status               ClusterReportedNodeState_StatusEnum `protobuf:"varint,4,opt,name=status,proto3,enum=lightbits.api.ClusterReportedNodeState_StatusEnum" json:"status,omitempty"`
	Error                string                              `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ClusterReportedNodeState) Reset()         { *m = ClusterReportedNodeState{} }
func (m *ClusterReportedNodeState) String() string { return proto.CompactTextString(m) }
func (*ClusterReportedNodeState) ProtoMessage()    {}
func (*ClusterReportedNodeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{8}
}

func (m *ClusterReportedNodeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterReportedNodeState.Unmarshal(m, b)
}
func (m *ClusterReportedNodeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterReportedNodeState.Marshal(b, m, deterministic)
}
func (m *ClusterReportedNodeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterReportedNodeState.Merge(m, src)
}
func (m *ClusterReportedNodeState) XXX_Size() int {
	return xxx_messageInfo_ClusterReportedNodeState.Size(m)
}
func (m *ClusterReportedNodeState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterReportedNodeState.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterReportedNodeState proto.InternalMessageInfo

func (m *ClusterReportedNodeState) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ClusterReportedNodeState) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ClusterReportedNodeState) GetState() ClusterReportedNodeState_StateEnum {
	if m != nil {
		return m.State
	}
	return ClusterReportedNodeState_Unknown
}

func (m *ClusterReportedNodeState) GetStatus() ClusterReportedNodeState_StatusEnum {
	if m != nil {
		return m.Status
	}
	return ClusterReportedNodeState_NoStatus
}

func (m *ClusterReportedNodeState) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LightOSVersion struct {
	TypeMeta             *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	Version              string    `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LightOSVersion) Reset()         { *m = LightOSVersion{} }
func (m *LightOSVersion) String() string { return proto.CompactTextString(m) }
func (*LightOSVersion) ProtoMessage()    {}
func (*LightOSVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{9}
}

func (m *LightOSVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightOSVersion.Unmarshal(m, b)
}
func (m *LightOSVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightOSVersion.Marshal(b, m, deterministic)
}
func (m *LightOSVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightOSVersion.Merge(m, src)
}
func (m *LightOSVersion) XXX_Size() int {
	return xxx_messageInfo_LightOSVersion.Size(m)
}
func (m *LightOSVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_LightOSVersion.DiscardUnknown(m)
}

var xxx_messageInfo_LightOSVersion proto.InternalMessageInfo

func (m *LightOSVersion) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *LightOSVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// an entity representing a physical server in duros cluster
type Server struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID     string    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// server friendly name
	Name                 string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UpgradeabilityState  UpgradeabilityEnum_State `protobuf:"varint,4,opt,name=UpgradeabilityState,proto3,enum=lightbits.api.UpgradeabilityEnum_State" json:"UpgradeabilityState,omitempty"`
	NodesUUIDs           []string                 `protobuf:"bytes,5,rep,name=NodesUUIDs,proto3" json:"NodesUUIDs,omitempty"`
	ServerExternalState  ServerStateEnum_State    `protobuf:"varint,6,opt,name=ServerExternalState,proto3,enum=lightbits.api.ServerStateEnum_State" json:"ServerExternalState,omitempty"`
	ServerEndpoints      []string                 `protobuf:"bytes,7,rep,name=ServerEndpoints,proto3" json:"ServerEndpoints,omitempty"`
	State                Server_StateEnum         `protobuf:"varint,8,opt,name=state,proto3,enum=lightbits.api.Server_StateEnum" json:"state,omitempty"`
	LightOSVersion       string                   `protobuf:"bytes,9,opt,name=LightOSVersion,proto3" json:"LightOSVersion,omitempty"`
	CreatePGs            bool                     `protobuf:"varint,10,opt,name=CreatePGs,proto3" json:"CreatePGs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{10}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *Server) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Server) GetUpgradeabilityState() UpgradeabilityEnum_State {
	if m != nil {
		return m.UpgradeabilityState
	}
	return UpgradeabilityEnum_None
}

func (m *Server) GetNodesUUIDs() []string {
	if m != nil {
		return m.NodesUUIDs
	}
	return nil
}

func (m *Server) GetServerExternalState() ServerStateEnum_State {
	if m != nil {
		return m.ServerExternalState
	}
	return ServerStateEnum_Unknown
}

func (m *Server) GetServerEndpoints() []string {
	if m != nil {
		return m.ServerEndpoints
	}
	return nil
}

func (m *Server) GetState() Server_StateEnum {
	if m != nil {
		return m.State
	}
	return Server_Unknown
}

func (m *Server) GetLightOSVersion() string {
	if m != nil {
		return m.LightOSVersion
	}
	return ""
}

func (m *Server) GetCreatePGs() bool {
	if m != nil {
		return m.CreatePGs
	}
	return false
}

type ServiceInfo struct {
	TypeMeta             *TypeMeta        `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	UUID                 string           `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	ServerName           string           `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServiceType          ServiceInfo_Type `protobuf:"varint,4,opt,name=serviceType,proto3,enum=lightbits.api.ServiceInfo_Type" json:"serviceType,omitempty"`
	Hostname             string           `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{11}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ServiceInfo) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ServiceInfo) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *ServiceInfo) GetServiceType() ServiceInfo_Type {
	if m != nil {
		return m.ServiceType
	}
	return ServiceInfo_ClusterManager
}

func (m *ServiceInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

// an entity representing a logical node in server
type DurosNode struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// service UUID
	UUID string `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// peer <ip>:<port> service datapath IP
	NvmeEndpoint        string   `protobuf:"bytes,3,opt,name=NvmeEndpoint,proto3" json:"NvmeEndpoint,omitempty"`
	ReplicationEndpoint string   `protobuf:"bytes,4,opt,name=ReplicationEndpoint,proto3" json:"ReplicationEndpoint,omitempty"`
	GrpcEndpoint        string   `protobuf:"bytes,5,opt,name=GrpcEndpoint,proto3" json:"GrpcEndpoint,omitempty"`
	FailureDomain       []string `protobuf:"bytes,6,rep,name=failureDomain,proto3" json:"failureDomain,omitempty"`
	// a set of physical capabilities like cores, numa-nodes, lightfield, interfaces, etc...
	Capabilities  map[string]string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CtrlId        uint32            `protobuf:"varint,8,opt,name=ctrlId,proto3" json:"ctrlId,omitempty"`
	FirstTimeInit bool              `protobuf:"varint,9,opt,name=firstTimeInit,proto3" json:"firstTimeInit,omitempty"`
	Hostname      string            `protobuf:"bytes,10,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ec            bool              `protobuf:"varint,11,opt,name=ec,proto3" json:"ec,omitempty"`
	MaxSlots      uint32            `protobuf:"varint,12,opt,name=maxSlots,proto3" json:"maxSlots,omitempty"`
	// node friendly name
	Name                 string       `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	HealthState          *HealthState `protobuf:"bytes,14,opt,name=healthState,proto3" json:"healthState,omitempty"`
	ServerUUID           string       `protobuf:"bytes,15,opt,name=serverUUID,proto3" json:"serverUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DurosNode) Reset()         { *m = DurosNode{} }
func (m *DurosNode) String() string { return proto.CompactTextString(m) }
func (*DurosNode) ProtoMessage()    {}
func (*DurosNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{12}
}

func (m *DurosNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurosNode.Unmarshal(m, b)
}
func (m *DurosNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurosNode.Marshal(b, m, deterministic)
}
func (m *DurosNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurosNode.Merge(m, src)
}
func (m *DurosNode) XXX_Size() int {
	return xxx_messageInfo_DurosNode.Size(m)
}
func (m *DurosNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DurosNode.DiscardUnknown(m)
}

var xxx_messageInfo_DurosNode proto.InternalMessageInfo

func (m *DurosNode) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *DurosNode) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DurosNode) GetNvmeEndpoint() string {
	if m != nil {
		return m.NvmeEndpoint
	}
	return ""
}

func (m *DurosNode) GetReplicationEndpoint() string {
	if m != nil {
		return m.ReplicationEndpoint
	}
	return ""
}

func (m *DurosNode) GetGrpcEndpoint() string {
	if m != nil {
		return m.GrpcEndpoint
	}
	return ""
}

func (m *DurosNode) GetFailureDomain() []string {
	if m != nil {
		return m.FailureDomain
	}
	return nil
}

func (m *DurosNode) GetCapabilities() map[string]string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *DurosNode) GetCtrlId() uint32 {
	if m != nil {
		return m.CtrlId
	}
	return 0
}

func (m *DurosNode) GetFirstTimeInit() bool {
	if m != nil {
		return m.FirstTimeInit
	}
	return false
}

func (m *DurosNode) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *DurosNode) GetEc() bool {
	if m != nil {
		return m.Ec
	}
	return false
}

func (m *DurosNode) GetMaxSlots() uint32 {
	if m != nil {
		return m.MaxSlots
	}
	return 0
}

func (m *DurosNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DurosNode) GetHealthState() *HealthState {
	if m != nil {
		return m.HealthState
	}
	return nil
}

func (m *DurosNode) GetServerUUID() string {
	if m != nil {
		return m.ServerUUID
	}
	return ""
}

type NodeState struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// service UUID
	UUID                 string         `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PeerName             string         `protobuf:"bytes,3,opt,name=peerName,proto3" json:"peerName,omitempty"`
	State                NodeStateEnum  `protobuf:"varint,4,opt,name=state,proto3,enum=lightbits.api.NodeStateEnum" json:"state,omitempty"`
	Status               NodeStatusEnum `protobuf:"varint,5,opt,name=status,proto3,enum=lightbits.api.NodeStatusEnum" json:"status,omitempty"`
	Progress             int32          `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Error                string         `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ReplicationEndpoint  string         `protobuf:"bytes,8,opt,name=replicationEndpoint,proto3" json:"replicationEndpoint,omitempty"`
	ReadOnly             bool           `protobuf:"varint,9,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeState) Reset()         { *m = NodeState{} }
func (m *NodeState) String() string { return proto.CompactTextString(m) }
func (*NodeState) ProtoMessage()    {}
func (*NodeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{13}
}

func (m *NodeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeState.Unmarshal(m, b)
}
func (m *NodeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeState.Marshal(b, m, deterministic)
}
func (m *NodeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeState.Merge(m, src)
}
func (m *NodeState) XXX_Size() int {
	return xxx_messageInfo_NodeState.Size(m)
}
func (m *NodeState) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeState.DiscardUnknown(m)
}

var xxx_messageInfo_NodeState proto.InternalMessageInfo

func (m *NodeState) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *NodeState) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *NodeState) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func (m *NodeState) GetState() NodeStateEnum {
	if m != nil {
		return m.State
	}
	return NodeStateEnum_Inactive
}

func (m *NodeState) GetStatus() NodeStatusEnum {
	if m != nil {
		return m.Status
	}
	return NodeStatusEnum_PowerupDatapath
}

func (m *NodeState) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *NodeState) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *NodeState) GetReplicationEndpoint() string {
	if m != nil {
		return m.ReplicationEndpoint
	}
	return ""
}

func (m *NodeState) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type NodeReportedStatesOfOtherNodes struct {
	TypeMeta             *TypeMeta       `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	SelfNodeUUID         string          `protobuf:"bytes,2,opt,name=selfNodeUUID,proto3" json:"selfNodeUUID,omitempty"`
	NodesStates          map[string]bool `protobuf:"bytes,3,rep,name=nodesStates,proto3" json:"nodesStates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NodeReportedStatesOfOtherNodes) Reset()         { *m = NodeReportedStatesOfOtherNodes{} }
func (m *NodeReportedStatesOfOtherNodes) String() string { return proto.CompactTextString(m) }
func (*NodeReportedStatesOfOtherNodes) ProtoMessage()    {}
func (*NodeReportedStatesOfOtherNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{14}
}

func (m *NodeReportedStatesOfOtherNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReportedStatesOfOtherNodes.Unmarshal(m, b)
}
func (m *NodeReportedStatesOfOtherNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReportedStatesOfOtherNodes.Marshal(b, m, deterministic)
}
func (m *NodeReportedStatesOfOtherNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReportedStatesOfOtherNodes.Merge(m, src)
}
func (m *NodeReportedStatesOfOtherNodes) XXX_Size() int {
	return xxx_messageInfo_NodeReportedStatesOfOtherNodes.Size(m)
}
func (m *NodeReportedStatesOfOtherNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReportedStatesOfOtherNodes.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReportedStatesOfOtherNodes proto.InternalMessageInfo

func (m *NodeReportedStatesOfOtherNodes) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *NodeReportedStatesOfOtherNodes) GetSelfNodeUUID() string {
	if m != nil {
		return m.SelfNodeUUID
	}
	return ""
}

func (m *NodeReportedStatesOfOtherNodes) GetNodesStates() map[string]bool {
	if m != nil {
		return m.NodesStates
	}
	return nil
}

type PeerProtectionGroupVersion struct {
	TypeMeta             *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	Value                uint64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PeerProtectionGroupVersion) Reset()         { *m = PeerProtectionGroupVersion{} }
func (m *PeerProtectionGroupVersion) String() string { return proto.CompactTextString(m) }
func (*PeerProtectionGroupVersion) ProtoMessage()    {}
func (*PeerProtectionGroupVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{15}
}

func (m *PeerProtectionGroupVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerProtectionGroupVersion.Unmarshal(m, b)
}
func (m *PeerProtectionGroupVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerProtectionGroupVersion.Marshal(b, m, deterministic)
}
func (m *PeerProtectionGroupVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerProtectionGroupVersion.Merge(m, src)
}
func (m *PeerProtectionGroupVersion) XXX_Size() int {
	return xxx_messageInfo_PeerProtectionGroupVersion.Size(m)
}
func (m *PeerProtectionGroupVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerProtectionGroupVersion.DiscardUnknown(m)
}

var xxx_messageInfo_PeerProtectionGroupVersion proto.InternalMessageInfo

func (m *PeerProtectionGroupVersion) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *PeerProtectionGroupVersion) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ClusterConnectionsMap struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	//map of hearbeat state for each nodeUUID as seen by cluster manager
	HeartbeatStates map[string]bool `protobuf:"bytes,2,rep,name=heartbeatStates,proto3" json:"heartbeatStates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	//map of connectivity decision as done by cluster manager
	ConnectivityStates   map[string]bool `protobuf:"bytes,3,rep,name=connectivityStates,proto3" json:"connectivityStates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClusterConnectionsMap) Reset()         { *m = ClusterConnectionsMap{} }
func (m *ClusterConnectionsMap) String() string { return proto.CompactTextString(m) }
func (*ClusterConnectionsMap) ProtoMessage()    {}
func (*ClusterConnectionsMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353194e0a1b6873, []int{16}
}

func (m *ClusterConnectionsMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterConnectionsMap.Unmarshal(m, b)
}
func (m *ClusterConnectionsMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterConnectionsMap.Marshal(b, m, deterministic)
}
func (m *ClusterConnectionsMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConnectionsMap.Merge(m, src)
}
func (m *ClusterConnectionsMap) XXX_Size() int {
	return xxx_messageInfo_ClusterConnectionsMap.Size(m)
}
func (m *ClusterConnectionsMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConnectionsMap.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConnectionsMap proto.InternalMessageInfo

func (m *ClusterConnectionsMap) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ClusterConnectionsMap) GetHeartbeatStates() map[string]bool {
	if m != nil {
		return m.HeartbeatStates
	}
	return nil
}

func (m *ClusterConnectionsMap) GetConnectivityStates() map[string]bool {
	if m != nil {
		return m.ConnectivityStates
	}
	return nil
}

func init() {
	proto.RegisterEnum("lightbits.api.NodeStateEnum", NodeStateEnum_name, NodeStateEnum_value)
	proto.RegisterEnum("lightbits.api.NodeStatusEnum", NodeStatusEnum_name, NodeStatusEnum_value)
	proto.RegisterEnum("lightbits.api.ServerStateEnum_State", ServerStateEnum_State_name, ServerStateEnum_State_value)
	proto.RegisterEnum("lightbits.api.ServerUpgradeStatus_UpgradeStatusEnum", ServerUpgradeStatus_UpgradeStatusEnum_name, ServerUpgradeStatus_UpgradeStatusEnum_value)
	proto.RegisterEnum("lightbits.api.UpgradeabilityEnum_State", UpgradeabilityEnum_State_name, UpgradeabilityEnum_State_value)
	proto.RegisterEnum("lightbits.api.ServiceStatus_StateEnum", ServiceStatus_StateEnum_name, ServiceStatus_StateEnum_value)
	proto.RegisterEnum("lightbits.api.ServiceStatus_ModeEnum", ServiceStatus_ModeEnum_name, ServiceStatus_ModeEnum_value)
	proto.RegisterEnum("lightbits.api.ClusterReportedNodeState_StateEnum", ClusterReportedNodeState_StateEnum_name, ClusterReportedNodeState_StateEnum_value)
	proto.RegisterEnum("lightbits.api.ClusterReportedNodeState_StatusEnum", ClusterReportedNodeState_StatusEnum_name, ClusterReportedNodeState_StatusEnum_value)
	proto.RegisterEnum("lightbits.api.Server_StateEnum", Server_StateEnum_name, Server_StateEnum_value)
	proto.RegisterEnum("lightbits.api.ServiceInfo_Type", ServiceInfo_Type_name, ServiceInfo_Type_value)
	proto.RegisterType((*ServerStateEnum)(nil), "lightbits.api.ServerStateEnum")
	proto.RegisterType((*ServerUpgradeStatus)(nil), "lightbits.api.ServerUpgradeStatus")
	proto.RegisterType((*UpgradeabilityEnum)(nil), "lightbits.api.UpgradeabilityEnum")
	proto.RegisterType((*ClusterInfo)(nil), "lightbits.api.ClusterInfo")
	proto.RegisterType((*ClusterPeer)(nil), "lightbits.api.ClusterPeer")
	proto.RegisterType((*ClusterPeerHeartbeat)(nil), "lightbits.api.ClusterPeerHeartbeat")
	proto.RegisterType((*PeerCommand)(nil), "lightbits.api.PeerCommand")
	proto.RegisterType((*ServiceStatus)(nil), "lightbits.api.ServiceStatus")
	proto.RegisterType((*ClusterReportedNodeState)(nil), "lightbits.api.ClusterReportedNodeState")
	proto.RegisterType((*LightOSVersion)(nil), "lightbits.api.LightOSVersion")
	proto.RegisterType((*Server)(nil), "lightbits.api.Server")
	proto.RegisterType((*ServiceInfo)(nil), "lightbits.api.ServiceInfo")
	proto.RegisterType((*DurosNode)(nil), "lightbits.api.DurosNode")
	proto.RegisterMapType((map[string]string)(nil), "lightbits.api.DurosNode.CapabilitiesEntry")
	proto.RegisterType((*NodeState)(nil), "lightbits.api.NodeState")
	proto.RegisterType((*NodeReportedStatesOfOtherNodes)(nil), "lightbits.api.NodeReportedStatesOfOtherNodes")
	proto.RegisterMapType((map[string]bool)(nil), "lightbits.api.NodeReportedStatesOfOtherNodes.NodesStatesEntry")
	proto.RegisterType((*PeerProtectionGroupVersion)(nil), "lightbits.api.PeerProtectionGroupVersion")
	proto.RegisterType((*ClusterConnectionsMap)(nil), "lightbits.api.ClusterConnectionsMap")
	proto.RegisterMapType((map[string]bool)(nil), "lightbits.api.ClusterConnectionsMap.ConnectivityStatesEntry")
	proto.RegisterMapType((map[string]bool)(nil), "lightbits.api.ClusterConnectionsMap.HeartbeatStatesEntry")
}

func init() { proto.RegisterFile("common_apis/cluster.proto", fileDescriptor_1353194e0a1b6873) }

var fileDescriptor_1353194e0a1b6873 = []byte{
	// 1724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x18, 0x4d, 0x6f, 0x1b, 0xc7,
	0x55, 0x5c, 0x7e, 0x88, 0x7c, 0x14, 0xa5, 0xf5, 0x48, 0x89, 0x19, 0x22, 0xb5, 0x85, 0x45, 0x9a,
	0x0a, 0x46, 0x4b, 0xa5, 0x4a, 0x0d, 0x24, 0xad, 0x91, 0xc2, 0x96, 0x54, 0x5b, 0x4e, 0x2d, 0x09,
	0x2b, 0x3b, 0x68, 0x03, 0x14, 0xce, 0x90, 0x1c, 0x51, 0xd3, 0xec, 0xce, 0x6c, 0x66, 0x86, 0x72,
	0x94, 0x7b, 0xd0, 0x1f, 0xd1, 0x4b, 0xd1, 0x63, 0xef, 0xbd, 0xf5, 0xd8, 0x7b, 0x7f, 0x40, 0xaf,
	0xfd, 0x1b, 0x05, 0x8a, 0xf9, 0xd8, 0xe5, 0xec, 0x8a, 0x8a, 0x6b, 0x45, 0xed, 0x6d, 0xdf, 0xc7,
	0xbc, 0xf7, 0xe6, 0x7d, 0xcf, 0xc2, 0x3b, 0x63, 0x9e, 0xa6, 0x9c, 0xbd, 0xc4, 0x19, 0x95, 0xdb,
	0xe3, 0x64, 0x26, 0x15, 0x11, 0xc3, 0x4c, 0x70, 0xc5, 0x51, 0x2f, 0xa1, 0xd3, 0x33, 0x35, 0xa2,
	0x4a, 0x0e, 0x71, 0x46, 0x07, 0x77, 0x7c, 0xce, 0x33, 0x82, 0x13, 0x75, 0xf6, 0x52, 0x2a, 0xac,
	0x88, 0x65, 0x1f, 0x0c, 0x7c, 0xba, 0xba, 0xc8, 0x48, 0x4a, 0x14, 0x76, 0xb4, 0xbe, 0x4f, 0x23,
	0xe7, 0x84, 0x29, 0xe9, 0x28, 0x77, 0xa7, 0x9c, 0x4f, 0x13, 0xb2, 0x6d, 0xa0, 0xd1, 0xec, 0x74,
	0x5b, 0xd1, 0x94, 0x48, 0x85, 0xd3, 0xcc, 0x32, 0x44, 0x7f, 0xa8, 0xc1, 0xda, 0x09, 0x11, 0xe7,
	0x44, 0x9c, 0x68, 0x65, 0xfb, 0x6c, 0x96, 0x46, 0x0a, 0x9a, 0x06, 0x40, 0x5d, 0x58, 0x7e, 0xc1,
	0xbe, 0x64, 0xfc, 0x15, 0x0b, 0x97, 0xd0, 0x0a, 0xb4, 0x77, 0x05, 0xc1, 0x8a, 0xb2, 0x69, 0x58,
	0xd3, 0xa4, 0x7d, 0x86, 0x47, 0x09, 0x99, 0x84, 0x81, 0x26, 0xed, 0x91, 0x84, 0x18, 0x52, 0x1d,
	0x01, 0xb4, 0x7e, 0x85, 0xa9, 0xa6, 0x34, 0x0c, 0x85, 0x4a, 0xcb, 0xd7, 0xd4, 0x90, 0x39, 0xa4,
	0xf9, 0x5a, 0xa8, 0x07, 0x1d, 0x4b, 0xd3, 0xe0, 0x72, 0xf4, 0xb7, 0x00, 0xd6, 0xad, 0x25, 0x2f,
	0xb2, 0xa9, 0xc0, 0x13, 0xa2, 0x6d, 0x98, 0x49, 0xf4, 0x21, 0xb4, 0xf5, 0x75, 0x9f, 0x11, 0x85,
	0xfb, 0xb5, 0xcd, 0xda, 0x56, 0x77, 0xe7, 0xf6, 0xb0, 0xe4, 0xba, 0xe1, 0x73, 0x47, 0x8e, 0x0b,
	0x46, 0x74, 0x07, 0x40, 0x5a, 0x59, 0x2f, 0x0e, 0xf6, 0xfa, 0xc1, 0x66, 0x6d, 0xab, 0x13, 0x7b,
	0x98, 0x39, 0xfd, 0x10, 0xa7, 0xa4, 0x5f, 0xf7, 0xe9, 0x1a, 0x83, 0x3e, 0x87, 0x5e, 0xc9, 0x8a,
	0x7e, 0x63, 0xb3, 0xb6, 0xb5, 0xba, 0xf3, 0xb3, 0x8a, 0xe6, 0x05, 0xf6, 0x0e, 0x4b, 0x90, 0xf6,
	0x67, 0x5c, 0x16, 0x15, 0x3d, 0x87, 0x5b, 0x97, 0x78, 0xca, 0xae, 0x6e, 0x43, 0xe3, 0x90, 0x33,
	0x12, 0xd6, 0x3c, 0x5f, 0x06, 0xda, 0x5f, 0xf6, 0x9c, 0x75, 0x73, 0x0f, 0x3a, 0x31, 0x19, 0x71,
	0x6e, 0xbc, 0xde, 0x88, 0x7e, 0x03, 0xc8, 0x49, 0xc5, 0x23, 0x9a, 0x50, 0x75, 0x61, 0x42, 0xf9,
	0x28, 0x0f, 0x65, 0x2e, 0x72, 0x09, 0xad, 0x41, 0xb7, 0x60, 0x4c, 0xb4, 0x0e, 0x04, 0xab, 0x87,
	0x9c, 0xf9, 0xb8, 0xc0, 0xd3, 0x5b, 0x8f, 0xbe, 0x81, 0xee, 0xae, 0xcd, 0xdc, 0x03, 0x76, 0xca,
	0xaf, 0x17, 0x0f, 0x04, 0x0d, 0x2f, 0x12, 0xe6, 0x1b, 0x45, 0xb0, 0x22, 0x67, 0x23, 0x79, 0x21,
	0x15, 0x49, 0x0f, 0xbf, 0x62, 0x2e, 0x0a, 0x25, 0x5c, 0x24, 0x0a, 0xdd, 0xc7, 0x84, 0x88, 0x9b,
	0xd3, 0x3d, 0x80, 0x76, 0x46, 0x4a, 0xd1, 0x2f, 0xe0, 0xe8, 0xaf, 0x35, 0xd8, 0xf0, 0x94, 0x3e,
	0x21, 0x58, 0xa8, 0x11, 0xc1, 0xea, 0xff, 0xa2, 0x1d, 0x7d, 0x04, 0x9d, 0xb3, 0x5c, 0xa3, 0xc9,
	0xba, 0xee, 0xce, 0x60, 0x68, 0xab, 0x78, 0x98, 0x57, 0xf1, 0xf0, 0x79, 0x5e, 0xc5, 0xf1, 0x9c,
	0x39, 0xfa, 0x53, 0x0d, 0xba, 0xda, 0xe0, 0x5d, 0x9e, 0xa6, 0x98, 0x4d, 0x6e, 0xce, 0xdc, 0x1f,
	0x43, 0xcb, 0x36, 0x95, 0x7e, 0x7d, 0xb3, 0xbe, 0xd5, 0xdd, 0xd9, 0xa8, 0x88, 0xd9, 0xd7, 0xc4,
	0xd8, 0xf1, 0x94, 0x2e, 0xd7, 0xa8, 0xb8, 0xf6, 0xef, 0x75, 0xe8, 0xe9, 0x9a, 0xa1, 0xe3, 0xef,
	0x55, 0xdd, 0x8b, 0x8c, 0x7c, 0x5d, 0x45, 0x3f, 0x80, 0xa6, 0x69, 0xa7, 0xae, 0x92, 0xdf, 0x5f,
	0x50, 0xc9, 0x85, 0x55, 0xc3, 0xa2, 0x17, 0xc6, 0xf6, 0x10, 0xda, 0x80, 0x26, 0x11, 0x82, 0x8b,
	0x7e, 0xd3, 0x08, 0xb6, 0x40, 0x39, 0x56, 0xad, 0x37, 0x88, 0x15, 0xfa, 0x18, 0x1a, 0x29, 0x9f,
	0x90, 0xfe, 0xb2, 0x31, 0xe6, 0x87, 0xdf, 0x69, 0xcc, 0x33, 0x3e, 0xb1, 0xb6, 0x98, 0x23, 0xd1,
	0x53, 0xe8, 0x14, 0xe6, 0x79, 0x75, 0xba, 0x84, 0x42, 0x58, 0x39, 0x60, 0x54, 0x51, 0x9c, 0xd0,
	0x6f, 0x6c, 0x93, 0x0e, 0x61, 0x65, 0x8f, 0xca, 0x31, 0x67, 0x8c, 0x8c, 0x55, 0xde, 0x43, 0x76,
	0x0b, 0xb0, 0x1e, 0xdd, 0x87, 0x76, 0x2e, 0x5d, 0x77, 0xa0, 0x63, 0x2c, 0x25, 0x3d, 0x27, 0x56,
	0xd6, 0x1e, 0xc1, 0x63, 0x45, 0xcf, 0xf3, 0x86, 0x0f, 0xd0, 0x7a, 0xa8, 0x61, 0x12, 0x06, 0xd1,
	0x3f, 0xea, 0xd0, 0x77, 0x15, 0x12, 0x93, 0x8c, 0x0b, 0x45, 0x26, 0x87, 0xdc, 0xb6, 0x33, 0x72,
	0x73, 0x11, 0x7d, 0x9c, 0x47, 0xac, 0x6e, 0x9c, 0xf4, 0xd3, 0x8a, 0x94, 0xab, 0x0c, 0xb8, 0x1c,
	0xbc, 0xa7, 0xd0, 0x92, 0x7e, 0x17, 0xdf, 0x79, 0x13, 0x49, 0xae, 0x87, 0x3b, 0x09, 0xf3, 0x44,
	0x68, 0x79, 0x89, 0x10, 0x7d, 0xe1, 0xc7, 0xa4, 0x3a, 0x35, 0x0f, 0x18, 0xb6, 0x8e, 0x2b, 0x39,
	0x51, 0xb3, 0x3d, 0xe5, 0x94, 0xd9, 0x66, 0xbe, 0x0e, 0x6b, 0x39, 0x5b, 0x4c, 0xbe, 0x9a, 0x11,
	0xa9, 0xc2, 0x86, 0x17, 0xdc, 0x66, 0xf4, 0x3b, 0x00, 0x6f, 0x5a, 0xac, 0x40, 0xfb, 0x90, 0x5b,
	0x38, 0x5c, 0xd2, 0x0d, 0xdc, 0x05, 0x95, 0x9e, 0x53, 0x75, 0x71, 0xf4, 0x69, 0x58, 0x43, 0xb7,
	0x61, 0xdd, 0xc7, 0x1d, 0x0b, 0x3e, 0x4a, 0x48, 0x1a, 0x06, 0x68, 0x03, 0xc2, 0x03, 0x29, 0x67,
	0x64, 0x62, 0x26, 0x36, 0xd1, 0x0d, 0x23, 0xac, 0x47, 0x2f, 0x61, 0xf5, 0xd7, 0xda, 0x27, 0x47,
	0x27, 0x9f, 0x11, 0x21, 0x29, 0x67, 0xd7, 0x0b, 0x63, 0x1f, 0x96, 0xdd, 0x79, 0x17, 0xc9, 0x1c,
	0x8c, 0xfe, 0xdc, 0x80, 0x96, 0x9d, 0x96, 0x37, 0x97, 0x20, 0x08, 0x1a, 0x6c, 0x5e, 0xec, 0xe6,
	0x1b, 0xfd, 0x16, 0xd6, 0xcb, 0x63, 0xf0, 0xc4, 0x2b, 0xfa, 0x1f, 0x55, 0xf4, 0x5c, 0x1e, 0x98,
	0x36, 0x79, 0xe2, 0x45, 0x32, 0x74, 0x87, 0xd1, 0xa9, 0x21, 0xb5, 0x6e, 0xd9, 0x6f, 0x6e, 0xd6,
	0x75, 0x87, 0x99, 0x63, 0xd0, 0x67, 0xf9, 0xfe, 0xb2, 0xff, 0xb5, 0x22, 0x82, 0xe1, 0xc4, 0xaa,
	0x6e, 0x19, 0xd5, 0xef, 0x2d, 0xdc, 0x1c, 0x8a, 0xa4, 0xc9, 0xf5, 0x2e, 0x10, 0x80, 0xb6, 0xf2,
	0x0d, 0x6d, 0x9f, 0x4d, 0x32, 0x4e, 0x75, 0x1f, 0x5e, 0x36, 0xca, 0xab, 0x68, 0x74, 0x3f, 0xaf,
	0x98, 0xb6, 0xd1, 0x79, 0x77, 0xa1, 0xce, 0xcb, 0xf5, 0xf1, 0x7e, 0x35, 0xf8, 0xfd, 0x8e, 0xf1,
	0x68, 0x35, 0x25, 0xde, 0x85, 0x8e, 0xd9, 0x00, 0xc9, 0xf1, 0x63, 0xd9, 0x87, 0xcd, 0xda, 0x56,
	0x3b, 0x9e, 0x23, 0xa2, 0x87, 0x57, 0xd6, 0xc0, 0x3c, 0xeb, 0x6b, 0xe5, 0x25, 0x26, 0x28, 0x95,
	0x47, 0x3d, 0xfa, 0x36, 0x80, 0xae, 0xeb, 0x7d, 0x37, 0xbb, 0x6a, 0xbc, 0x6e, 0x38, 0x3c, 0x84,
	0xae, 0xb4, 0x7a, 0xb5, 0x40, 0x97, 0x2d, 0x77, 0x17, 0x77, 0x65, 0x6d, 0x99, 0xd1, 0x1b, 0xfb,
	0x67, 0xf4, 0xd8, 0x3b, 0xe3, 0x52, 0x99, 0x84, 0xb4, 0x43, 0xa2, 0x80, 0xa3, 0x21, 0x34, 0x0c,
	0x8f, 0x2e, 0x54, 0xdb, 0x6b, 0x9e, 0x61, 0x86, 0xa7, 0x44, 0xd8, 0xe2, 0x75, 0xc9, 0x96, 0xe3,
	0x6a, 0xd1, 0xbf, 0x1b, 0xd0, 0xd9, 0x9b, 0x09, 0x2e, 0x75, 0x76, 0xdd, 0xe8, 0xc2, 0x75, 0x78,
	0x9e, 0x92, 0x3c, 0x5f, 0xf2, 0x85, 0xcb, 0xc7, 0xa1, 0x0f, 0x60, 0x3d, 0x26, 0x59, 0x42, 0xc7,
	0x58, 0x51, 0xce, 0x0a, 0x56, 0x3b, 0xc8, 0x17, 0x91, 0xb4, 0xd4, 0xc7, 0x22, 0x1b, 0x17, 0xac,
	0xf6, 0xf2, 0x25, 0x1c, 0x7a, 0x0f, 0x7a, 0xa7, 0x98, 0x26, 0x33, 0x41, 0xf6, 0x78, 0x8a, 0x29,
	0xeb, 0xb7, 0x4c, 0x02, 0x97, 0x91, 0xe8, 0x10, 0x56, 0xc6, 0x38, 0xb3, 0x35, 0x47, 0x89, 0xcd,
	0xf2, 0xee, 0xce, 0xbd, 0xca, 0x65, 0x0b, 0xc7, 0x0c, 0x77, 0x3d, 0xe6, 0x7d, 0xa6, 0xc4, 0x45,
	0x5c, 0x3a, 0x8f, 0xde, 0x86, 0xd6, 0x58, 0x89, 0xe4, 0x60, 0x62, 0xea, 0xa1, 0x17, 0x3b, 0xc8,
	0x58, 0x43, 0x85, 0x54, 0x7a, 0x32, 0xeb, 0x89, 0x69, 0xd2, 0xbd, 0x1d, 0x97, 0x91, 0xa5, 0x80,
	0x42, 0x39, 0xa0, 0x68, 0x15, 0x02, 0x32, 0xee, 0x77, 0xcd, 0xb1, 0x80, 0x8c, 0x35, 0x6f, 0x8a,
	0xbf, 0x3e, 0x49, 0xb8, 0x92, 0xfd, 0x15, 0xa3, 0xab, 0x80, 0x8b, 0x2e, 0xd5, 0xf3, 0xba, 0xd4,
	0x03, 0xe8, 0xda, 0x27, 0x9e, 0x6d, 0x11, 0xab, 0x6e, 0x75, 0x28, 0x5f, 0xf4, 0xc9, 0x9c, 0x23,
	0xf6, 0xd9, 0x2b, 0x8f, 0x9b, 0xb5, 0xea, 0xe3, 0x66, 0xf0, 0x4b, 0xb8, 0x75, 0xc9, 0x35, 0x28,
	0x84, 0xfa, 0x97, 0xe4, 0xc2, 0x24, 0x50, 0x27, 0xd6, 0x9f, 0x7a, 0x94, 0x9d, 0xe3, 0x64, 0x46,
	0x5c, 0x8e, 0x58, 0xe0, 0xe7, 0xc1, 0x47, 0xb5, 0xe8, 0x9f, 0x01, 0x74, 0xfe, 0x07, 0x03, 0xfd,
	0xbb, 0xd6, 0xde, 0x9d, 0xf2, 0x7a, 0xf6, 0x6e, 0x45, 0x43, 0x61, 0x8d, 0xdf, 0xb7, 0xee, 0x17,
	0x73, 0xbd, 0x69, 0x0e, 0xfd, 0xe0, 0x8a, 0x43, 0x95, 0x11, 0xae, 0xcd, 0x10, 0x7c, 0x2a, 0x88,
	0x94, 0xa6, 0x39, 0x37, 0xe3, 0x02, 0x9e, 0x8f, 0xf7, 0x65, 0x7f, 0xcf, 0xfb, 0x00, 0xd6, 0xc5,
	0x82, 0xa2, 0x68, 0xdb, 0xa2, 0x58, 0x40, 0xd2, 0x3a, 0x04, 0xc1, 0x93, 0x23, 0x96, 0x5c, 0xb8,
	0xec, 0x2a, 0xe0, 0xe8, 0x8f, 0x01, 0xdc, 0xd1, 0xa6, 0xe5, 0xfb, 0x86, 0xb9, 0x97, 0x3c, 0x3a,
	0x3d, 0x52, 0x67, 0x44, 0x98, 0x79, 0x72, 0x3d, 0x97, 0xeb, 0xf7, 0x14, 0x49, 0x4e, 0xb5, 0x04,
	0xcf, 0xf5, 0x25, 0x1c, 0xfa, 0x02, 0xba, 0x4c, 0x6b, 0xb0, 0x3a, 0xdd, 0x3e, 0xff, 0xc9, 0x02,
	0xbf, 0x5d, 0x6d, 0x9c, 0x21, 0x3b, 0x01, 0xb6, 0xea, 0x7c, 0x91, 0x83, 0x4f, 0x20, 0xac, 0x32,
	0xbc, 0x2e, 0xf7, 0xda, 0x7e, 0xee, 0x4d, 0x61, 0xa0, 0x77, 0x92, 0x63, 0xc1, 0x95, 0x5e, 0x5e,
	0x38, 0x7b, 0x2c, 0xf8, 0x2c, 0xfb, 0x5e, 0x5b, 0x49, 0x49, 0x59, 0xc3, 0x29, 0x8b, 0xfe, 0x52,
	0x87, 0xb7, 0x5c, 0x37, 0xce, 0x37, 0x25, 0xce, 0xe4, 0x33, 0x9c, 0x5d, 0x4f, 0xc9, 0x18, 0xd6,
	0x8a, 0xf5, 0xde, 0x79, 0x37, 0x30, 0xde, 0xfd, 0x78, 0xf1, 0xb6, 0x59, 0xd6, 0x39, 0x7c, 0x52,
	0x3e, 0x6b, 0x1d, 0x5b, 0x95, 0x88, 0x12, 0x40, 0x63, 0x6f, 0xab, 0x2b, 0x45, 0xf1, 0xc1, 0x7f,
	0xa5, 0x67, 0xf7, 0xd2, 0x71, 0xab, 0x6a, 0x81, 0xdc, 0xc1, 0x23, 0xd8, 0x58, 0x64, 0xd6, 0x9b,
	0x84, 0x73, 0xb0, 0x0f, 0xb7, 0xaf, 0x50, 0xf9, 0x26, 0x62, 0xee, 0x7d, 0x5b, 0x83, 0x5e, 0xa9,
	0x07, 0x94, 0x36, 0x87, 0x25, 0xb4, 0x0a, 0xf0, 0xd0, 0x7f, 0xad, 0x78, 0xcb, 0x75, 0xa0, 0x89,
	0x31, 0x19, 0xcd, 0x68, 0xe2, 0xfe, 0x9c, 0xac, 0x41, 0xd7, 0xc1, 0x7b, 0x9c, 0x11, 0xbb, 0x68,
	0xbb, 0x05, 0xa5, 0x79, 0xe9, 0xe5, 0xd3, 0xf2, 0xd6, 0xf0, 0xe5, 0x7b, 0xff, 0xaa, 0xc1, 0x6a,
	0xb9, 0xad, 0xe8, 0xd5, 0xfd, 0x98, 0xbf, 0x22, 0x62, 0x96, 0xed, 0x61, 0x85, 0x33, 0xac, 0xce,
	0xc2, 0x25, 0xf4, 0x0e, 0xbc, 0x55, 0x41, 0x3a, 0x11, 0xe6, 0x51, 0x76, 0x72, 0xc1, 0xc6, 0x05,
	0x73, 0xa0, 0x57, 0x00, 0x67, 0xcf, 0x89, 0xc2, 0xc2, 0xbc, 0xcc, 0xd0, 0x2d, 0xe8, 0x39, 0x5c,
	0xf1, 0x2f, 0x6d, 0x03, 0x42, 0x87, 0xda, 0xe5, 0x69, 0xa6, 0x97, 0xf7, 0x49, 0xd8, 0xd4, 0xd8,
	0xe7, 0x04, 0x8b, 0x09, 0x7f, 0xc5, 0x0a, 0x91, 0x2d, 0x34, 0x80, 0xb7, 0xab, 0xd8, 0xfc, 0x0e,
	0x56, 0xf4, 0xef, 0x39, 0x65, 0xb9, 0xb6, 0xb6, 0xf6, 0x90, 0xbe, 0x95, 0x76, 0x19, 0x99, 0x84,
	0x9d, 0x47, 0x9f, 0x7e, 0x7e, 0x30, 0xa5, 0xea, 0x6c, 0x36, 0x1a, 0x8e, 0x79, 0xba, 0x5d, 0xe4,
	0x55, 0x82, 0x47, 0x72, 0x0e, 0xfd, 0x04, 0x67, 0x74, 0x7b, 0x4a, 0xd8, 0xf6, 0x94, 0x27, 0x98,
	0x4d, 0xb7, 0xbd, 0x9f, 0x90, 0xbf, 0xf0, 0xbe, 0x47, 0x2d, 0xf3, 0x14, 0xfe, 0xf0, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0xcf, 0x0d, 0xce, 0x0c, 0x15, 0x00, 0x00,
}
