// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_apis/events.proto

package common_apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventReasonEnum int32

const (
	// volume related reasons
	EventReasonEnum_VolumeCreated      EventReasonEnum = 0
	EventReasonEnum_VolumeCreateFailed EventReasonEnum = 1
	EventReasonEnum_VolumeUpdated      EventReasonEnum = 2
	EventReasonEnum_VolumeUpdateFailed EventReasonEnum = 3
	EventReasonEnum_VolumeDeleted      EventReasonEnum = 4
	EventReasonEnum_VolumeDeleteFailed EventReasonEnum = 5
	// protection group related reasons
	EventReasonEnum_ProtectionGroupCreated EventReasonEnum = 10
	EventReasonEnum_ProtectionGroupUpdated EventReasonEnum = 11
	//peers related reasons
	EventReasonEnum_PeerCreated       EventReasonEnum = 12
	EventReasonEnum_PeerCreatedFailed EventReasonEnum = 13
	EventReasonEnum_PeerDeleted       EventReasonEnum = 14
	EventReasonEnum_PeerDeletedFailed EventReasonEnum = 15
)

var EventReasonEnum_name = map[int32]string{
	0:  "VolumeCreated",
	1:  "VolumeCreateFailed",
	2:  "VolumeUpdated",
	3:  "VolumeUpdateFailed",
	4:  "VolumeDeleted",
	5:  "VolumeDeleteFailed",
	10: "ProtectionGroupCreated",
	11: "ProtectionGroupUpdated",
	12: "PeerCreated",
	13: "PeerCreatedFailed",
	14: "PeerDeleted",
	15: "PeerDeletedFailed",
}

var EventReasonEnum_value = map[string]int32{
	"VolumeCreated":          0,
	"VolumeCreateFailed":     1,
	"VolumeUpdated":          2,
	"VolumeUpdateFailed":     3,
	"VolumeDeleted":          4,
	"VolumeDeleteFailed":     5,
	"ProtectionGroupCreated": 10,
	"ProtectionGroupUpdated": 11,
	"PeerCreated":            12,
	"PeerCreatedFailed":      13,
	"PeerDeleted":            14,
	"PeerDeletedFailed":      15,
}

func (x EventReasonEnum) String() string {
	return proto.EnumName(EventReasonEnum_name, int32(x))
}

func (EventReasonEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cac353bddee5f823, []int{0}
}

type EventSource_ComponentEnum int32

const (
	EventSource_NodeManager    EventSource_ComponentEnum = 0
	EventSource_ClusterManager EventSource_ComponentEnum = 1
	EventSource_APIService     EventSource_ComponentEnum = 2
)

var EventSource_ComponentEnum_name = map[int32]string{
	0: "NodeManager",
	1: "ClusterManager",
	2: "APIService",
}

var EventSource_ComponentEnum_value = map[string]int32{
	"NodeManager":    0,
	"ClusterManager": 1,
	"APIService":     2,
}

func (x EventSource_ComponentEnum) String() string {
	return proto.EnumName(EventSource_ComponentEnum_name, int32(x))
}

func (EventSource_ComponentEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cac353bddee5f823, []int{0, 0}
}

// the component that generated this event.
type EventSource struct {
	// reporting component ID
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Component from which the event is generated.
	Component EventSource_ComponentEnum `protobuf:"varint,2,opt,name=component,proto3,enum=lightbits.api.EventSource_ComponentEnum" json:"component,omitempty"`
	// Node name on which the event is generated.
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventSource) Reset()         { *m = EventSource{} }
func (m *EventSource) String() string { return proto.CompactTextString(m) }
func (*EventSource) ProtoMessage()    {}
func (*EventSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac353bddee5f823, []int{0}
}

func (m *EventSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSource.Unmarshal(m, b)
}
func (m *EventSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSource.Marshal(b, m, deterministic)
}
func (m *EventSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSource.Merge(m, src)
}
func (m *EventSource) XXX_Size() int {
	return xxx_messageInfo_EventSource.Size(m)
}
func (m *EventSource) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSource.DiscardUnknown(m)
}

var xxx_messageInfo_EventSource proto.InternalMessageInfo

func (m *EventSource) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *EventSource) GetComponent() EventSource_ComponentEnum {
	if m != nil {
		return m.Component
	}
	return EventSource_NodeManager
}

func (m *EventSource) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

// The resource this event is refering to.
type EventSubject struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// resource ID
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventSubject) Reset()         { *m = EventSubject{} }
func (m *EventSubject) String() string { return proto.CompactTextString(m) }
func (*EventSubject) ProtoMessage()    {}
func (*EventSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac353bddee5f823, []int{1}
}

func (m *EventSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSubject.Unmarshal(m, b)
}
func (m *EventSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSubject.Marshal(b, m, deterministic)
}
func (m *EventSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSubject.Merge(m, src)
}
func (m *EventSubject) XXX_Size() int {
	return xxx_messageInfo_EventSubject.Size(m)
}
func (m *EventSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSubject.DiscardUnknown(m)
}

var xxx_messageInfo_EventSubject proto.InternalMessageInfo

func (m *EventSubject) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *EventSubject) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type Event struct {
	TypeMeta *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	// event id
	UUID string `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// command this event is related to, optional.
	CommandID string `protobuf:"bytes,3,opt,name=commandID,proto3" json:"commandID,omitempty"`
	// machine understandable string that gives the reason for the transition into the resource’s current status.
	Reason EventReasonEnum `protobuf:"varint,4,opt,name=reason,proto3,enum=lightbits.api.EventReasonEnum" json:"reason,omitempty"`
	// A human-readable description of the status of this operation.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// The object that this event is about.
	Subject *EventSubject `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// Describe the source that triggered this event.
	Source               *EventSource `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac353bddee5f823, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *Event) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Event) GetCommandID() string {
	if m != nil {
		return m.CommandID
	}
	return ""
}

func (m *Event) GetReason() EventReasonEnum {
	if m != nil {
		return m.Reason
	}
	return EventReasonEnum_VolumeCreated
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetSubject() *EventSubject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Event) GetSource() *EventSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func init() {
	proto.RegisterEnum("lightbits.api.EventReasonEnum", EventReasonEnum_name, EventReasonEnum_value)
	proto.RegisterEnum("lightbits.api.EventSource_ComponentEnum", EventSource_ComponentEnum_name, EventSource_ComponentEnum_value)
	proto.RegisterType((*EventSource)(nil), "lightbits.api.EventSource")
	proto.RegisterType((*EventSubject)(nil), "lightbits.api.EventSubject")
	proto.RegisterType((*Event)(nil), "lightbits.api.Event")
}

func init() { proto.RegisterFile("common_apis/events.proto", fileDescriptor_cac353bddee5f823) }

var fileDescriptor_cac353bddee5f823 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0xac, 0x7f, 0xd8, 0xe9, 0xfa, 0x67, 0x96, 0x18, 0x51, 0x41, 0x68, 0xea, 0x55,
	0x85, 0x44, 0x22, 0x75, 0x82, 0x1b, 0xae, 0xa0, 0xdd, 0x50, 0x85, 0x86, 0xaa, 0x8c, 0x82, 0xc4,
	0x0d, 0x72, 0x92, 0xa3, 0x34, 0x28, 0xb1, 0x23, 0xdb, 0x99, 0xc4, 0xab, 0xf0, 0x0a, 0x3c, 0x06,
	0x2f, 0x86, 0xe2, 0xc4, 0x4d, 0x36, 0x95, 0xbb, 0xdd, 0x39, 0x9f, 0x7f, 0xfe, 0x7c, 0xce, 0x77,
	0x62, 0x70, 0x42, 0x9e, 0x65, 0x9c, 0xfd, 0xa0, 0x79, 0x22, 0x3d, 0xbc, 0x43, 0xa6, 0xa4, 0x9b,
	0x0b, 0xae, 0x38, 0x19, 0xa6, 0x49, 0xbc, 0x53, 0x41, 0xa2, 0xa4, 0x4b, 0xf3, 0x64, 0x3a, 0x6d,
	0x83, 0xea, 0x57, 0x8e, 0x19, 0x2a, 0x5a, 0xa1, 0xb3, 0xbf, 0x16, 0x0c, 0xae, 0xca, 0xb3, 0xb7,
	0xbc, 0x10, 0x21, 0x12, 0x02, 0x9d, 0xed, 0x76, 0xbd, 0x72, 0xac, 0x0b, 0x6b, 0x7e, 0xe2, 0xeb,
	0x35, 0xb9, 0x86, 0x93, 0x90, 0x67, 0x39, 0x67, 0xc8, 0x94, 0x63, 0x5f, 0x58, 0xf3, 0xd1, 0x62,
	0xee, 0xde, 0xbb, 0xc2, 0x6d, 0x59, 0xb8, 0x4b, 0xc3, 0x5e, 0xb1, 0x22, 0xf3, 0x9b, 0xa3, 0xa5,
	0xf7, 0x8e, 0x4b, 0xe5, 0x1c, 0x57, 0xde, 0xe5, 0x7a, 0xb6, 0x82, 0xe1, 0x3d, 0x9e, 0x8c, 0x61,
	0xf0, 0x99, 0x47, 0x78, 0x43, 0x19, 0x8d, 0x51, 0x4c, 0x8e, 0x08, 0x81, 0xd1, 0x32, 0x2d, 0xa4,
	0x42, 0x61, 0x34, 0x8b, 0x8c, 0x00, 0xde, 0x6f, 0xd6, 0xb7, 0x28, 0xee, 0x92, 0x10, 0x27, 0xf6,
	0xec, 0x1b, 0x9c, 0x56, 0x15, 0x14, 0xc1, 0x4f, 0x0c, 0x15, 0xb9, 0x84, 0x27, 0x65, 0x9f, 0x37,
	0xa8, 0xa8, 0xee, 0x64, 0xb0, 0x78, 0xf6, 0xa0, 0xe0, 0x2f, 0xf5, 0xb6, 0xbf, 0x07, 0xf7, 0xad,
	0xdb, 0x4d, 0xeb, 0xb3, 0x3f, 0x36, 0x74, 0xb5, 0xf3, 0xa3, 0x59, 0x92, 0x17, 0x3a, 0xcd, 0x8c,
	0xb2, 0x68, 0xbd, 0xaa, 0xa3, 0x68, 0x04, 0xf2, 0x16, 0x7a, 0x02, 0xa9, 0xe4, 0xcc, 0xe9, 0xe8,
	0xa0, 0x5f, 0x1e, 0x0a, 0xda, 0xd7, 0x84, 0x8e, 0xb7, 0xa6, 0x89, 0x03, 0xfd, 0x0c, 0xa5, 0xa4,
	0x31, 0x3a, 0x5d, 0xed, 0x69, 0x3e, 0xc9, 0x1b, 0xe8, 0xcb, 0x2a, 0x16, 0xa7, 0xa7, 0xeb, 0x7e,
	0x7e, 0x70, 0x76, 0x15, 0xe2, 0x1b, 0x96, 0x2c, 0xa0, 0x27, 0xf5, 0x3c, 0x9d, 0xbe, 0x3e, 0x35,
	0xfd, 0xff, 0xc4, 0xfd, 0x9a, 0x7c, 0xf5, 0xdb, 0x86, 0xf1, 0x83, 0x02, 0xc9, 0x19, 0x0c, 0xbf,
	0xf2, 0xb4, 0xc8, 0x70, 0x29, 0x90, 0x2a, 0x8c, 0x26, 0x47, 0xe4, 0x1c, 0x48, 0x5b, 0xba, 0xa6,
	0x49, 0x8a, 0xd1, 0xc4, 0x6a, 0xd0, 0x6d, 0x1e, 0x69, 0xd4, 0x6e, 0xd0, 0x4a, 0xaa, 0xd1, 0xe3,
	0x06, 0x5d, 0x61, 0x8a, 0x25, 0xda, 0x69, 0xd0, 0x4a, 0xaa, 0xd1, 0x2e, 0x99, 0xc2, 0xf9, 0x46,
	0x70, 0x85, 0xa1, 0x4a, 0x38, 0xfb, 0x28, 0x78, 0x91, 0x9b, 0x4a, 0xe0, 0xc0, 0x9e, 0xb9, 0x7a,
	0x50, 0xfe, 0x88, 0x1b, 0x44, 0x61, 0xe0, 0x53, 0xf2, 0x14, 0xce, 0x5a, 0x42, 0xed, 0x3f, 0x34,
	0x9c, 0x29, 0x64, 0x64, 0xb8, 0x5a, 0xa8, 0xb9, 0xf1, 0x87, 0x4f, 0xdf, 0xd7, 0x71, 0xa2, 0x76,
	0x45, 0xe0, 0x86, 0x3c, 0xf3, 0xf6, 0x61, 0xa6, 0x34, 0x90, 0xcd, 0xd7, 0x6b, 0x9a, 0x27, 0x5e,
	0x8c, 0xcc, 0x8b, 0x79, 0x4a, 0x59, 0xec, 0xb5, 0x5e, 0xee, 0xbb, 0xd6, 0x3a, 0xe8, 0xe9, 0xd7,
	0x7b, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xc4, 0xd8, 0x58, 0x04, 0x04, 0x00, 0x00,
}
