// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_apis/health_state.proto

package common_apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// an entity in health history
type HealthHistoryEntry struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State                uint64               `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HealthHistoryEntry) Reset()         { *m = HealthHistoryEntry{} }
func (m *HealthHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*HealthHistoryEntry) ProtoMessage()    {}
func (*HealthHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37603b54d2d66a, []int{0}
}

func (m *HealthHistoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthHistoryEntry.Unmarshal(m, b)
}
func (m *HealthHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthHistoryEntry.Marshal(b, m, deterministic)
}
func (m *HealthHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthHistoryEntry.Merge(m, src)
}
func (m *HealthHistoryEntry) XXX_Size() int {
	return xxx_messageInfo_HealthHistoryEntry.Size(m)
}
func (m *HealthHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_HealthHistoryEntry proto.InternalMessageInfo

func (m *HealthHistoryEntry) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *HealthHistoryEntry) GetState() uint64 {
	if m != nil {
		return m.State
	}
	return 0
}

// an entity representing health of a service
type HealthState struct {
	CurrentState         uint64                `protobuf:"varint,1,opt,name=currentState,proto3" json:"currentState,omitempty"`
	HealthHistory        []*HealthHistoryEntry `protobuf:"bytes,2,rep,name=healthHistory,proto3" json:"healthHistory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HealthState) Reset()         { *m = HealthState{} }
func (m *HealthState) String() string { return proto.CompactTextString(m) }
func (*HealthState) ProtoMessage()    {}
func (*HealthState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37603b54d2d66a, []int{1}
}

func (m *HealthState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthState.Unmarshal(m, b)
}
func (m *HealthState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthState.Marshal(b, m, deterministic)
}
func (m *HealthState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthState.Merge(m, src)
}
func (m *HealthState) XXX_Size() int {
	return xxx_messageInfo_HealthState.Size(m)
}
func (m *HealthState) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthState.DiscardUnknown(m)
}

var xxx_messageInfo_HealthState proto.InternalMessageInfo

func (m *HealthState) GetCurrentState() uint64 {
	if m != nil {
		return m.CurrentState
	}
	return 0
}

func (m *HealthState) GetHealthHistory() []*HealthHistoryEntry {
	if m != nil {
		return m.HealthHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthHistoryEntry)(nil), "lightbits.api.HealthHistoryEntry")
	proto.RegisterType((*HealthState)(nil), "lightbits.api.HealthState")
}

func init() { proto.RegisterFile("common_apis/health_state.proto", fileDescriptor_7a37603b54d2d66a) }

var fileDescriptor_7a37603b54d2d66a = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0xeb, 0x30,
	0x14, 0xc5, 0x95, 0xbe, 0x3e, 0x24, 0x1c, 0xba, 0x58, 0x0c, 0x51, 0x07, 0x08, 0x99, 0xb2, 0x60,
	0x4b, 0x65, 0x41, 0x62, 0x43, 0x42, 0x14, 0xb1, 0x05, 0x26, 0x96, 0xca, 0x0e, 0xc6, 0xb6, 0xe4,
	0x7f, 0xb2, 0x6f, 0x86, 0xf2, 0xe9, 0x11, 0x8e, 0xda, 0x26, 0x62, 0xf3, 0xb1, 0x7f, 0xf7, 0xdc,
	0x73, 0x8c, 0xae, 0x7a, 0x6f, 0xad, 0x77, 0x3b, 0x16, 0x74, 0xa2, 0x4a, 0x30, 0x03, 0x6a, 0x97,
	0x80, 0x81, 0x20, 0x21, 0x7a, 0xf0, 0x78, 0x65, 0xb4, 0x54, 0xc0, 0x35, 0x24, 0xc2, 0x82, 0x5e,
	0x5f, 0x4b, 0xef, 0xa5, 0x11, 0x34, 0x3f, 0xf2, 0xe1, 0x8b, 0x82, 0xb6, 0x22, 0x01, 0xb3, 0x61,
	0xe4, 0x9b, 0x4f, 0x84, 0xb7, 0xd9, 0x65, 0xab, 0x13, 0xf8, 0xb8, 0x7f, 0x72, 0x10, 0xf7, 0xf8,
	0x1e, 0x9d, 0x1f, 0xc1, 0xaa, 0xa8, 0x8b, 0xb6, 0xdc, 0xac, 0xc9, 0x68, 0x45, 0x0e, 0x56, 0xe4,
	0xfd, 0x40, 0x74, 0x27, 0x18, 0x5f, 0xa2, 0xff, 0x39, 0x4e, 0xb5, 0xa8, 0x8b, 0x76, 0xd9, 0x8d,
	0xa2, 0xf9, 0x46, 0xe5, 0xb8, 0xe5, 0xed, 0x57, 0xe2, 0x06, 0x5d, 0xf4, 0x43, 0x8c, 0xc2, 0x41,
	0xd6, 0x79, 0xc3, 0xb2, 0x9b, 0xdd, 0xe1, 0x67, 0xb4, 0x52, 0xd3, 0x60, 0xd5, 0xa2, 0xfe, 0xd7,
	0x96, 0x9b, 0x1b, 0x32, 0x2b, 0x48, 0xfe, 0x86, 0xef, 0xe6, 0x73, 0x8f, 0xaf, 0x1f, 0x2f, 0x52,
	0x83, 0x1a, 0x38, 0xe9, 0xbd, 0xa5, 0xc7, 0x69, 0xc3, 0x78, 0x3a, 0xa9, 0x5b, 0x16, 0x34, 0x95,
	0xc2, 0x51, 0xe9, 0x0d, 0x73, 0x92, 0x4e, 0x7e, 0xf9, 0x61, 0x72, 0xe6, 0x67, 0xb9, 0xfd, 0xdd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x0f, 0x37, 0xe4, 0x87, 0x01, 0x00, 0x00,
}
