// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_apis/nullable_types.proto

package common_apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringList struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb750f895613660d, []int{0}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Int64List struct {
	Values               []uint64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb750f895613660d, []int{1}
}

func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (m *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(m, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetValues() []uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*StringList)(nil), "lightbits.api.StringList")
	proto.RegisterType((*Int64List)(nil), "lightbits.api.Int64List")
}

func init() { proto.RegisterFile("common_apis/nullable_types.proto", fileDescriptor_fb750f895613660d) }

var fileDescriptor_fb750f895613660d = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x8b, 0x4f, 0x2c, 0xc8, 0x2c, 0xd6, 0xcf, 0x2b, 0xcd, 0xc9, 0x49, 0x4c, 0xca, 0x49,
	0x8d, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0xc9,
	0x4c, 0xcf, 0x28, 0x49, 0xca, 0x2c, 0x29, 0xd6, 0x4b, 0x2c, 0xc8, 0x54, 0x52, 0xe1, 0xe2, 0x0a,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xf7, 0xc9, 0x2c, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0x4b, 0xcc,
	0x29, 0x4d, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf2, 0x94, 0x94, 0xb9, 0x38,
	0x3d, 0xf3, 0x4a, 0xcc, 0x4c, 0xb0, 0x28, 0x62, 0x81, 0x29, 0x72, 0xf2, 0x8e, 0xf2, 0x4c, 0xcf,
	0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x87, 0x5b, 0x93, 0x93, 0x98, 0x54, 0x8c,
	0xe0, 0xe9, 0x26, 0x16, 0x64, 0xea, 0xa7, 0xa7, 0xe6, 0xe9, 0xa7, 0xe7, 0xe7, 0x24, 0xe6, 0xa5,
	0xeb, 0x23, 0xb9, 0xd7, 0x1a, 0x89, 0x9d, 0xc4, 0x06, 0x76, 0xad, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x59, 0x6d, 0x49, 0xd6, 0xd1, 0x00, 0x00, 0x00,
}
