// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_apis/typemeta.proto

package common_apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TypeMeta describes an individual object in an API response or request
// with strings representing the type of the object and its API schema version.
// Structures that are versioned or persisted should inline TypeMeta.
type TypeMeta struct {
	// kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// apiVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	ApiVersion           string   `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeMeta) Reset()         { *m = TypeMeta{} }
func (m *TypeMeta) String() string { return proto.CompactTextString(m) }
func (*TypeMeta) ProtoMessage()    {}
func (*TypeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f8787f448695aa, []int{0}
}

func (m *TypeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeMeta.Unmarshal(m, b)
}
func (m *TypeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeMeta.Marshal(b, m, deterministic)
}
func (m *TypeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeMeta.Merge(m, src)
}
func (m *TypeMeta) XXX_Size() int {
	return xxx_messageInfo_TypeMeta.Size(m)
}
func (m *TypeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TypeMeta proto.InternalMessageInfo

func (m *TypeMeta) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TypeMeta) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

type Unknown struct {
	// base type for decoding the type metadata before decoding the data it self.
	TypeMeta             *TypeMeta `protobuf:"bytes,1,opt,name=typeMeta,proto3" json:"typeMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Unknown) Reset()         { *m = Unknown{} }
func (m *Unknown) String() string { return proto.CompactTextString(m) }
func (*Unknown) ProtoMessage()    {}
func (*Unknown) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f8787f448695aa, []int{1}
}

func (m *Unknown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unknown.Unmarshal(m, b)
}
func (m *Unknown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unknown.Marshal(b, m, deterministic)
}
func (m *Unknown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unknown.Merge(m, src)
}
func (m *Unknown) XXX_Size() int {
	return xxx_messageInfo_Unknown.Size(m)
}
func (m *Unknown) XXX_DiscardUnknown() {
	xxx_messageInfo_Unknown.DiscardUnknown(m)
}

var xxx_messageInfo_Unknown proto.InternalMessageInfo

func (m *Unknown) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

type ErrorMessage struct {
	// base type for decoding the type metadata before decoding the data it self.
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f8787f448695aa, []int{2}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*TypeMeta)(nil), "lightbits.api.TypeMeta")
	proto.RegisterType((*Unknown)(nil), "lightbits.api.Unknown")
	proto.RegisterType((*ErrorMessage)(nil), "lightbits.api.ErrorMessage")
}

func init() { proto.RegisterFile("common_apis/typemeta.proto", fileDescriptor_52f8787f448695aa) }

var fileDescriptor_52f8787f448695aa = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4b, 0x03, 0x41,
	0x10, 0xc5, 0x89, 0xf8, 0x27, 0x8e, 0xda, 0x2c, 0x82, 0xc1, 0x42, 0xe4, 0xb0, 0xb0, 0x71, 0x17,
	0x4c, 0x29, 0xa4, 0x10, 0x2c, 0x44, 0xd2, 0x04, 0xb5, 0xb0, 0x91, 0xb9, 0x38, 0x6c, 0x86, 0xdc,
	0xcd, 0x2c, 0xbb, 0x23, 0x92, 0x6f, 0x2f, 0x9e, 0x31, 0x5e, 0xba, 0xf7, 0x66, 0x86, 0xdf, 0x1b,
	0x1e, 0x9c, 0xcf, 0xb5, 0x6d, 0x55, 0xde, 0x31, 0x71, 0x09, 0xb6, 0x4a, 0xd4, 0x92, 0xa1, 0x4f,
	0x59, 0x4d, 0xdd, 0x49, 0xc3, 0x71, 0x61, 0x35, 0x5b, 0xf1, 0x98, 0xb8, 0x9a, 0xc0, 0xf0, 0x79,
	0x95, 0x68, 0x4a, 0x86, 0xce, 0xc1, 0xee, 0x92, 0xe5, 0x63, 0x34, 0xb8, 0x1c, 0x5c, 0x1f, 0xce,
	0x3a, 0xed, 0x2e, 0x00, 0x30, 0xf1, 0x2b, 0xe5, 0xc2, 0x2a, 0xa3, 0x9d, 0x6e, 0xd3, 0x9b, 0x54,
	0x13, 0x38, 0x78, 0x91, 0xa5, 0xe8, 0x97, 0xb8, 0x31, 0x0c, 0x6d, 0x8d, 0xea, 0x10, 0x47, 0xb7,
	0x67, 0x7e, 0x2b, 0xcc, 0xff, 0x25, 0xcd, 0x36, 0x87, 0xd5, 0x15, 0x1c, 0x3f, 0xe4, 0xac, 0x79,
	0x4a, 0xa5, 0x60, 0x24, 0x77, 0x0a, 0x7b, 0xf4, 0xe3, 0xd7, 0x4f, 0xfc, 0x9a, 0xfb, 0xa7, 0xb7,
	0xc7, 0xc8, 0xb6, 0xf8, 0xac, 0xfd, 0x5c, 0xdb, 0xb0, 0x81, 0x36, 0x58, 0x97, 0x7f, 0x77, 0x83,
	0x89, 0x43, 0x24, 0x09, 0x51, 0x1b, 0x94, 0x18, 0x7a, 0x25, 0xdc, 0xf5, 0x74, 0xbd, 0xdf, 0x15,
	0x31, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x06, 0x61, 0xbb, 0x26, 0x01, 0x00, 0x00,
}
